<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0 " />
<meta name="google-site-verification" content="AkLz6AV9QFs84jCT5SREIj3bsX7H6udJZrWijhdaheM" />
<meta name="google-site-verification" content="Ax0nvtnGWl45SE8qRjK7o8xSpxVwizfjL3mo9FRMnSI" />
  <meta name="google-translate-customization" content="86891d37e9507069-65398aa04931c2f8-g2e9ef316f8e456fb-e" />
<title><?php echo $this->getTitle() ?></title>
<meta name="description" content="<?php echo htmlspecialchars($this->getDescription()) ?>" />
<meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()) ?>" />
<meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()) ?>" />
<link rel="icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<link rel="shortcut icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />

<!--[if lt IE 7]>
<script type="text/javascript">
//<![CDATA[
    var BLANK_URL = '<?php echo $this->helper('core/js')->getJsUrl('blank.html') ?>';
    var BLANK_IMG = '<?php echo $this->helper('core/js')->getJsUrl('spacer.gif') ?>';
//]]>
</script>
<![endif]-->
<?php echo $this->getCssJsHtml() ?>
<?php echo $this->getChildHtml() ?>
<?php echo $this->helper('core/js')->getTranslatorScript() ?>
<?php echo $this->getIncludes() ?>
