<?php /** @var $this Ey_GTM_Block_Checkout_Cart */ ?>

<?php if($product = $this->getRemovedItem()): ?>
    <script type="text/javascript">
        dataLayer.push({
            'event': 'removeFromCart',
            'ecommerce': {
                'remove': {
                    'products': [{
                        'name': '<?php echo $product['name'] ?>',
                        'id': '<?php echo $product['sku'] ?>',
                        'price': '<?php echo $product['price'] ?>',
                        'variant': '<?php echo $product['variant'] ?>',
                        'quantity': <?php echo $product['quantity'] ?>
                    }]
                }
            }
        });
    </script>
<?php endif; ?>