<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<?php $routeName = Mage::app()->getRequest()->getRouteName(); if($routeName == 'catalogsearch'): ?>
    <?php echo $this->getToolbarHtml() ?>
<?php endif; ?>
 
    <div class="col-main">
        <?php $_collectionSize = $_productCollection->count() ?>
        <?php $_columnCount = $this->getcolumnscount();  if(empty($_columnCount)) { $_columnCount = 3;} ?>
        <h2 class="product-list-title"><?php echo $this->__("Featured")?></h2>
        <ul class="product-list list-view featured">
        <?php $i=0; foreach ($_productCollection as $_product): ?>
            <li>
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="img"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(137,137); ?>" width="137" height="137" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                <div class="txt">
                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                    <?php $smalldescription = $_product->getsmalldescription(); if(!empty($smalldescription)): 
                        $smalldescription = $_product->getsmalldescription();
                        $smalldescription = trim($smalldescription);
                        $limit = 200;
                        if (strlen($smalldescription) > $limit) {
                            $smalldescription = substr($smalldescription, 0, strrpos(substr($smalldescription, 0, $limit), ' '));
                            $smalldescription = $smalldescription.'...';
                        } ?>

                        <div class="short-description">
                            <div class="std">
                              <p><?php echo $smalldescription; ?></p>
                            </div>
                        </div>
                    <?php endif; ?>
                </div>
            </li>
        <?php endforeach ?>
        </ul>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    </div>
<?php endif; ?>
