<?php
$_productCollection=$this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');

$currentCountry = Mage::getModel('core/session')->getData('current_country');
$countryCode = $currentCountry['code'];

if(in_array($countryCode, array('US','CA'))){
    $showPrice = true;
}else{
    $showPrice = false;
}


?>
<?php if(!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <?php $routeName = Mage::app()->getRequest()->getRouteName(); if($routeName == 'catalogsearch'): ?>
        <?php echo $this->getToolbarHtml() ?>
    <?php endif; ?>

    <div class="col-main">
        <?php $_collectionSize = $_productCollection->count() ?>
        <?php $_columnCount = $this->getcolumnscount();  if(empty($_columnCount)) { $_columnCount = 3;} ?>
        <h2 class="product-list-title"><?php echo $this->__("Product Lines")?></h2>
        <ul class="product-list list-view">
            <?php $i=0; foreach ($_productCollection as $_product): ?>
                <li itemscope itemtype="http://schema.org/Product">
                    <a itemprop="url" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" data-sku="<?php echo $_product->getSku() ?>" class="img"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(137,137); ?>" width="137" height="137" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                    <div class="txt">
                        <div class="col-1">
                            <h2 class="product-name" itemprop="name"><a href="<?php echo $_product->getProductUrl() ?>" data-sku="<?php echo $_product->getSku() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                            <span itemscope itemtype="http://schema.org/Brand" style="display:none;">
                                <span itemprop="name">Omni International "The Homogenizer Company"</span>
                            </span>
                            <span style="display:none;">Model: 
                                <span itemprop="model"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></span>
                            </span>
                            <?php $smalldescription = $_product->getsmalldescription(); if(!empty($smalldescription)):
                                $smalldescription = $_product->getsmalldescription();
                                $smalldescription = trim($smalldescription);
                                $limit = 200;
                                if (strlen($smalldescription) > $limit) {
                                    $smalldescription = substr($smalldescription, 0, strrpos(substr($smalldescription, 0, $limit), ' '));
                                    $smalldescription = $smalldescription.'...';
                                } ?>

                                <div class="short-description">
                                    <div class="std">
                                        <meta itemprop="description" content="<?php echo $smalldescription; ?>">
                                        <p><?php echo $smalldescription; ?></p>
                                    </div>
                                </div>
                            <?php endif; ?>
                            <!-- Price -->

                            <?php if($_product->_data['price'] != 0): ?>
                                <span itemprop="offers" itemscope itemtype="http://schema.org/Offer">
                                    <meta itemprop="priceCurrency" content="USD"/>
                                    <meta itemprop="price" content="<?php echo $_product->getFinalPrice() ?>" />
                                    <meta itemprop="itemCondition" href="http://schema.org/NewCondition" content="New" />
                                </span>
                                <?php echo $this->getPriceHtml($_product, false) ?>
                            <?php endif; ?>
                        </div>
                        <div class="col-2">
                            <?php if($_product->isSaleable()): ?>
                                <div class="add-to-cart">
                                    <!-- Cart -->
                                    <?php
                                    if($block = Mage::app()->getLayout()->createBlock('qquoteadv/qquotebtn')){
                                        echo $block->setData('product', $_product)
                                            ->setTemplate('qquoteadv/catalog/product/c2qBtnList.phtml')
                                            ->toHtml();
                                    }
                                    ?>
                                </div>
                            <?php endif; ?>
                        </div>

                    </div>



                </li>
            <?php endforeach ?>
        </ul>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
        <?php $routeName = Mage::app()->getRequest()->getRouteName(); if($routeName == 'catalogsearch'): ?>
            <?php echo $this->getToolbarHtml() ?>
        <?php endif; ?>
    </div><!-- lalalalalalallala -->
<?php endif; ?>
