<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');

    $currentCountry = Mage::getModel('core/session')->getData('current_country');
    $countryCode = $currentCountry['code'];

    if(in_array($countryCode, array('US','CA'))){
        $showPrice = true;
    }else{
        $showPrice = false;
    }



?>
<?php if(!$_productCollection->count()): ?>


<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>

 
    <div class="col-main">
        <?php $_collectionSize = $_productCollection->count() ?>
        <?php $_columnCount = $this->getcolumnscount();  if(empty($_columnCount)) { $_columnCount = 3;} ?>
        <h2 class="product-list-title"><?php echo $this->__("Product Lines")?></h2>
        <ul class="product-list list-view">
        <?php $i=0; foreach ($_productCollection as $_product): ?>
            <li>
                <?php $cats = $_product->getCategoryIds();
                foreach ($cats as $category_id) {
                    $_cat = Mage::getModel('catalog/category')->load($category_id) ;
                    echo $_cat->getName();
                } ?>
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="img"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(137,137); ?>" width="137" height="137" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
            </li>
        <?php endforeach ?>
        </ul>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
        <?php $routeName = Mage::app()->getRequest()->getRouteName(); if($routeName == 'catalogsearch'): ?>
            <?php echo $this->getToolbarHtml() ?>
        <?php endif; ?>
    </div><!-- lalalalalalallala -->
<?php endif; ?>
