<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
    jQuery(document).ready(function () {
        if(jQuery(".applicationnotes").length == 0 ){
            jQuery('.add-nav li.applications').css('display','none');
        }

        if(jQuery(".productbrochure").length == 0 && jQuery(".productmanuals").length == 0 && jQuery(".repairinstallationguide").length == 0 && jQuery(".quickstartguides").length == 0){
            jQuery('.add-nav li.literature').css('display','none');
        }

        jQuery(".add-nav li.general-info, .add-nav li.video, .add-nav li.success-stories, .add-nav li.specifications, .add-nav li.accessories").click(function(e) {
            jQuery(".applicationnotes, .productbrochure, .productmanuals,.repairinstallationguide,.quickstartguides").removeClass('active');
        });
        jQuery(".add-nav li.applications").click(function(e) {
            jQuery(".productbrochure, .productmanuals,.repairinstallationguide,.quickstartguides").removeClass('active');
            jQuery(".applicationnotes").addClass('active');
        });
        jQuery(".add-nav li.literature").click(function(e) {
            jQuery(".applicationnotes").removeClass('active');
            jQuery(".productbrochure, .productmanuals,.repairinstallationguide,.quickstartguides").addClass('active');
        });

        // store the currently selected tab in the uri param
        jQuery(".add-nav li").click(function() {
            var li = jQuery(this);
            setTimeout(function() {
                if (li.hasClass('active')) {
                    var id = li.find('> a').attr("href").substr(1);
                    queryString.push('tab',id);
                };
            },500);
        });

        function getUrlParameter(key) {
            var sPageURL = window.location.search.substring(1);
            var sURLVariables = sPageURL.split('&');
            for (var i = 0; i < sURLVariables.length; i++)
            {
                var sParameterName = sURLVariables[i].split('=');
                if (sParameterName[0] == key)
                {
                    return sParameterName[1];
                }
            }
        }

        // on load of the page: switch to the currently selected tab
        var tab = getUrlParameter('tab');
        if (tab) {
            jQuery('.add-nav li a[href="#' + tab + '"]').click();
        };
    });
</script>

<div class="product-main-info-wrapper">
    <div class="container">
        <div class="product-gallery" id="bg">
            <section class="slide" >
                <?php echo $this->getChildHtml('media') ?>
                <?php $imagetext = $_product->getimagetext(); if(!empty($imagetext)): ?>
                    <div class="container">
                        <div class="text-holder">
                            <?php // echo $imagetext;
                            ?>
                        </div>
                    </div>
                <?php endif ?>

                <script type="text/javascript">
                    (function($){
                        $(document).ready(function() {
                            $('.thumbnails a').click(function(e){
                                e.preventDefault();
                                $('.thumbnails a.active').removeClass('active');
                                $(this).addClass('active');
                                switchImage($(this));
                            });
                            function switchImage(obj){
                                var obj = $(obj);
                                var productImage = $('.product-image img');
                                var newImageClone = obj.find('img').clone();
                                productImage.replaceWith(newImageClone);
                            }
                        });
                    })(jQuery);
                </script>

                <?php if (false): ?>
                    <!-- Bring in gallery Images    -->
                    <?php $_gallery = Mage::getModel('catalog/product')->load($_product->getId())->getMediaGalleryImages(); ?>
                    <?php $imgcount = Mage::getModel('catalog/product')->load($_product->getId())->getMediaGalleryImages()->count();?>
                    <?php if($imgcount >1): ?>
                        <div class="more-views">
                            <script type="text/javascript">

                            </script>
                            <ul class="thumbnails">
                                <?php foreach ($_gallery as $_image ):  ?>
                                    <li>
                                        <a href="#">
                                            <img src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail', $_image->getFile())->resize(400, 300); ?>"  alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>" />
                                        </a>
                                    </li>
                                <?php endforeach;  ?>
                            </ul>
                        </div>
                    <?php endif; ?>
                <?php endif; ?>



            </section>
        </div>
        <div class="product-order-wrapper" itemscope itemtype="http://schema.org/Product">
            <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
                <div class="no-display">
                    <input type="hidden" name="product" value="<?php $_product->getId() ?>" />
                    <input type="hidden" name="related_product" id="related-products-field" value="" />
                </div>

                <div class="options-block">
                    <!-- not needed
                    <h2 class="product-name"></h2>
                    -->
                    <meta itemprop="name" content="<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>"/>
                    <meta itemprop="url" content="<?php echo $_SERVER['QUERY_STRING'] ?>"/>
                    <meta itemprop="description" content="<?php $_product->getDescription(); ?>" />
                    <meta itemprop="brand" content='Omni International, "The Homogenizer Company"'/>
                    <span itemprop="offers" itemscope itemtype="http://schema.org/Offer">
                        <meta itemprop="priceCurrency" content="USD"/>
                        <meta itemprop="price" content="<?php echo $_product->getFinalPrice(); ?>" />
                        <meta itemprop="itemCondition" href="http://schema.org/NewCondition" content="New" />
                        <meta itemprop="availability" href="http://schema.org/InStock" content="In stock" />
                    </span>
                    <h2 class="product-name">Order This Product</h2>
                    <!-- start sku-->
                    <?php if ($_product->getTypeId() != 'configurable'):?>
                        <div class="product-sku row">
                            <strong><label><?php echo $this->__('SKU: ') ?></label></strong>
                            <?php echo nl2br($_product->getSku()) ?><br>
                        </div>
                    <?php endif;?>
                    <!-- end sku-->
                    <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                        <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
                    <?php endif;?>
                    <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                        <!-- <div class="product-options" id="product-options-wrapper">
                             <dl class="last">
                                  <dt><label>Generator Probes Sold Separately. Select a Stainless Steel Probe From The Accessories Tab Below</label></dt>
                           </dl>
                      </div> -->
                        <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
                    <?php endif;?>
                    <!-- <?php echo $this->getChildHtml('other');?> -->

                    <div class="row">
                        <?php if($_product->isSaleable()): ?>
                            <div class="add-to-cart">
								
								<?php
								$currentCountry = Mage::getSingleton('core/session')->getData('current_country');
								$hideCartBtn = !is_null($currentCountry) && !empty($currentCountry) && $currentCountry['code'] != 'US' && $currentCountry['code'] != 'CA' ? true : false;
								?>								
								
                                <!-- Price -->
                                <?php if (!$hideCartBtn && $_product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_BUNDLE || $_product->isGrouped()): ?>
                                    <?php echo $this->getChildHtml('product_type_data') ?>
                                    <?php echo $this->getChildHtml('extrahint') ?>
                                <?php endif; ?>

                                <!-- Cart -->                                
								<?php if(!$_product->isGrouped()): ?>
									<label for="qty"><?php echo $this->__('Quantity:') ?></label>
									<input type="text" name="qty" id="qty" maxlength="12" value="<?php echo max($this->getProductDefaultQty() * 1, 1) ?>" title="<?php echo $this->__('Qty') ?>" class="input-text qty" />
								<?php endif; ?>
								<?php if($_product->getPrice() != 0): ?>
									<?php if(!$hideCartBtn): ?>
									<?php echo $this->getPriceHtml($_product, false) ?>
									<!-- <a href="<?php echo $this->getUrl('distributor-locator'); ?>" target="_blank" class="contact-for-quote"><?php echo $this->__('Contact a distributor for a quote'); ?></a> -->
									<button type="button" title="<?php echo $this->__('Add to Cart'); ?>" class="button btn-cart" onclick="productAddToCartForm.submit(this); ga('send', 'event', 'Add-to-cart', 'Product-added', '<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>');"><span><span><?php echo $this->__('Add to Cart'); ?></span></span></button>
									<?php endif; ?>
								<?php endif; ?>

                                <!-- quote button -->
                                <?php
                                $action = $this->helper('qquoteadv/catalog_product_data')->getAddToQuoteAction($_product->getId());
                                ?>

                                <button type="button" title="<?php echo Mage::helper('qquoteadv')->__("Add to Quote"); ?>"
                                        class="button btn-cart btn-quote"
                                        onclick="<?php echo $action; ?>">
                                    <span><span><?php echo Mage::helper('qquoteadv')->__("Add to Quote"); ?></span></span></button>
                                <!--END Request a Quote -->
                            </div>


                        <?php endif; ?>
                    </div>





                </div>
            </form>
            <script type="text/javascript">
                //<![CDATA[
                var productAddToCartForm = new VarienForm('product_addtocart_form');
                productAddToCartForm.submit = function(button, url) {
                    if (this.validator.validate()) {
                        var form = this.form;
                        var oldUrl = form.action;

                        if (url) {
                            form.action = url;
                        }
                        var e = null;
                        try {
                            this.form.submit();
                        } catch (e) {
                        }
                        this.form.action = oldUrl;
                        if (e) {
                            throw e;
                        }

                        if (button && button != 'undefined') {
                            button.disabled = true;
                        }
                    }
                }.bind(productAddToCartForm);

                productAddToCartForm.submitLight = function(button, url){
                    if(this.validator) {
                        var nv = Validation.methods;
                        delete Validation.methods['required-entry'];
                        delete Validation.methods['validate-one-required'];
                        delete Validation.methods['validate-one-required-by-name'];
                        // Remove custom datetime validators
                        for (var methodName in Validation.methods) {
                            if (methodName.match(/^validate-datetime-.*/i)) {
                                delete Validation.methods[methodName];
                            }
                        }

                        if (this.validator.validate()) {
                            if (url) {
                                this.form.action = url;
                            }
                            this.form.submit();
                        }
                        Object.extend(Validation.methods, nv);
                    }
                }.bind(productAddToCartForm);
                //]]>
            </script>
        </div>
    </div>
</div>
<?php
$_helper = $this->helper('catalog/output');
$specification = $_product->getspecifications();
$applications = $_product->getapplications();
$fullapplication = $_product->getviewourfullapplication();
$supportmaterials = $_product->getsupportmaterials();
$faq = $_product->getfaq();
$itsProducts = array();

foreach ($_product->getRelatedLinkCollection() as $link) {
    $relatedData[$link->getLinkedProductId()]['position'] = $link->getPosition();
    $itsProducts[] = $link->getLinkedProductId();
}
$related = $itsProducts;

?>
<div class="info-wrapper">

    <div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
    <div class="main-tab container">
        <div class="main-column materials-box">
            <nav class="add-nav">
                <div class="container">
                    <ul>
                        <li class="green general-info active"><a href="#order"><?php echo $this->__('General Info'); ?><em></em></a></li>
                        <?php if(!empty($specification)):  ?>
                            <li class="blue specifications"><a href="#specifications"><?php echo $this->__('Specifications'); ?><em></em></a></li>
                        <?php endif; ?>
                        <?php if(count($related)):  ?>
                            <li class="yellow accessories"><a href="#accessories"><?php echo $this->__('Accessories'); ?><em></em></a></li>
                        <?php endif; ?>
                        <?php //if(!empty($applications)):  ?>
                        <li class="light-blue applications"><a href="#"><?php echo $this->__('Applications'); ?><em></em></a></li>
                        <?php //endif; ?>
                        <?php if(!empty($fullapplication)):  ?>
                            <li class="blue video"><a href="#fullapplication"><?php echo $this->__('Video'); ?><em></em></a></li>
                        <?php endif; ?>
                        <?php //if(!empty($supportmaterials)):  ?>
                        <li class="yellow literature"><a href="#"><?php echo $this->__('Literature'); ?><em></em></a></li>
                        <?php //endif; ?>
                        <?php if(!empty($faq)):  ?>
                            <li class="light-blue success-stories"><a href="#faq"><?php echo $this->__('Testimonials'); ?><em></em></a></li>
                        <?php endif; ?>
                    </ul>
                </div>
            </nav>
            <div id="order" >
                <div id="description">
                    <?php echo $_product->getDescription(); ?>
                </div>
            </div>
            <?php echo $this->getChildHtml('product_additional_data') ?>
            <?php if(!empty($specification)) : ?>
                <div id="specifications">
                    <div class="sub-title">
                        <h2><?php echo $this->__('Specifications'); ?></h2>
                    </div>
                    <div class="box-collateral box-description">
                        <?php echo $_helper->productAttribute($_product, $specification, 'specifications') ?>
                    </div>
                </div>
            <?php endif; ?>

            <!--Related Products-->
            <?php if($this->getChildHtml('related') != ''): ?>
                <div id="accessories">
                    <div class="sub-title">
                        <h2><?php echo $this->__('Accessories'); ?></h2>

                    </div>

                    <?php echo $this->getChildHtml('related');?>
                </div>
            <?php endif; ?>
            <!-- End Related Products-->

            <!-- video -->
            <?php if(!empty($fullapplication)) : ?>
                <div id="fullapplication">
                    <div class="sub-title">
                        <h2><?php echo $this->__('Video'); ?></h2>
                    </div>
                    <div class="materials-box">
                        <?php echo $_helper->productAttribute($_product, $fullapplication, 'fullapplication') ?>
                    </div>
                </div>
            <?php endif; ?>
            <!-- end video-->

            <?php if(!empty($faq)) : ?>
                <div id="faq">
                    <div class="sub-title">
                        <h2><?php echo $this->__('Success Stories'); ?></h2>
                    </div>
                    <div class="materials-box question">
                        <?php echo $_helper->productAttribute($_product, $faq, 'faq') ?>
                    </div>
                </div>
            <?php endif; ?>
        </div>
            <aside class="col-right sidebar">
                <!-- Order form use to be here: not needed -->
                <!--Start Static Block -->
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('get_help')->toHtml() ?>
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('news_events')->toHtml() ?>
                <!--End Static Block-->
            </aside>
        </div>
         <!--is here -->
        
    </div>

</div>
