<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div class="title-wrapper product-title">
    <div class="page-title title-buttons">
        <div class="container">
            <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>

        </div>
    </div>
</div>
<div class="product-main-info-wrapper">
    <div class="container">
        <div class="product-gallery" id="bg">
            <section class="slide" >
                <?php echo $this->getChildHtml('media') ?>
                <?php $imagetext = $_product->getimagetext(); if(!empty($imagetext)): ?>
                <div class="container">
                    <div class="text-holder">
                        <?php // echo $imagetext;                
                        ?>                
                    </div>
                </div>
                <?php endif ?>
                
                
                <script src="http://code.jquery.com/jquery-1.9.min.js"></script>
                <script type="text/javascript">
                (function($){
                    $(document).ready(function() {
                        $('.thumbnails a').click(function(e){
                            e.preventDefault();
                            $('.thumbnails a.active').removeClass('active');
                            $(this).addClass('active');
                            switchImage($(this));
                        });
                        function switchImage(obj){
                            var obj = $(obj);
                            var productImage = $('.product-image img');
                            var newImageClone = obj.find('img').clone();
                            productImage.replaceWith(newImageClone);
                        }
                    });
                })(jQuery);
                </script>
                
                                <!-- Bring in gallery Images    -->
                            <?php $_gallery = Mage::getModel('catalog/product')->load($_product->getId())->getMediaGalleryImages(); ?>
                            <?php $imgcount = Mage::getModel('catalog/product')->load($_product->getId())->getMediaGalleryImages()->count();?>
                            <?php if($imgcount >1): ?>
                                <div class="more-views">  
                                <script type="text/javascript">

                                </script>                
                                   <ul class="thumbnails">
                                    <?php foreach ($_gallery as $_image ):  ?>
                                        <li>
                                            <a href="#"> 
                                                <img src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail', $_image->getFile())->resize(400, 300); ?>"  alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>" />
                                            </a>
                                        </li>
                                     <?php endforeach;  ?>
                                    </ul>
                                </div>
                            <?php endif; ?>

                
                
            </section>
        </div>
        <div class="product-order-wrapper">
            <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
                <div class="no-display">
                    <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
                    <input type="hidden" name="related_product" id="related-products-field" value="" />
                </div>
                
                <div class="options-block">
                    <!-- not needed
                    <h2 class="product-name"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h2>
                    -->
                    <h2 class="product-name">Order this Product</h2>
                    <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                        <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
                    <?php endif;?>
                    <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                        <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
                    <?php endif;?>
                    <?php echo $this->getChildHtml('other');?>

                    <div class="row">
                        <!-- start sku--> <b>
<label><?php echo $this->__('SKU: ') ?></b></label><?php echo nl2br($_product->getSku()) ?></br>
                        <!-- end sku--> 

                        
                        
                        <?php if($_product->isSaleable()): ?>
                            <div class="add-to-cart">
                                <?php if(!$_product->isGrouped()): ?>
                                    <label for="qty"><?php echo $this->__('Quantity:') ?></label>
                                    <input type="text" name="qty" id="qty" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>" title="<?php echo $this->__('Qty') ?>" class="input-text qty" />
                                <?php endif; ?>
                                <!-- Price -->
                                <?php if ($_product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_BUNDLE || $_product->isGrouped()): ?>
                                    <?php echo $this->getChildHtml('product_type_data') ?>
                                    <?php echo $this->getChildHtml('extrahint') ?>
                                <?php else: ?>
                                    <?php echo $this->getPriceHtml($_product, false) ?>
                                <?php endif; ?>
                                <button type="button" title="<?php echo $this->__('Add to Cart'); ?>" class="button btn-cart" onclick="productAddToCartForm.submit(this)"><span><span><?php echo $this->__('Add to Cart'); ?></span></span></button>
                            </div>
                    
                    
                        <?php endif; ?>
                    </div>
                
                   <!-- START Request a Quote -->
                <script type="text/javascript" src="<?php echo $this->getBaseUrl() ?>skin/frontend/base/default/js/qquoteadv.js"></script>
                 
<div class="row" ><?php echo Mage::app()->getLayout()->createBlock('qquoteadv/qquotebtn')

->setData('product', $_product)

->setTemplate('qquoteadv/catalog/product/view/addtoquoteadv.phtml')->toHtml(); ?>
            </div>
            
                  <!--END Request a Quote -->
                
                </div>
            </form>
            <script type="text/javascript">
            //<![CDATA[
                var productAddToCartForm = new VarienForm('product_addtocart_form');
                productAddToCartForm.submit = function(button, url) {
                    if (this.validator.validate()) {
                        var form = this.form;
                        var oldUrl = form.action;
        
                        if (url) {
                           form.action = url;
                        }
                        var e = null;
                        try {
                            this.form.submit();
                        } catch (e) {
                        }
                        this.form.action = oldUrl;
                        if (e) {
                            throw e;
                        }
        
                        if (button && button != 'undefined') {
                            button.disabled = true;
                        }
                    }
                }.bind(productAddToCartForm);
        
                productAddToCartForm.submitLight = function(button, url){
                    if(this.validator) {
                        var nv = Validation.methods;
                        delete Validation.methods['required-entry'];
                        delete Validation.methods['validate-one-required'];
                        delete Validation.methods['validate-one-required-by-name'];
                        // Remove custom datetime validators
                        for (var methodName in Validation.methods) {
                            if (methodName.match(/^validate-datetime-.*/i)) {
                                delete Validation.methods[methodName];
                            }
                        }
        
                        if (this.validator.validate()) {
                            if (url) {
                                this.form.action = url;
                            }
                            this.form.submit();
                        }
                        Object.extend(Validation.methods, nv);
                    }
                }.bind(productAddToCartForm);
            //]]>
            </script>
        </div>
    </div>
</div>
<?php
    $_helper = $this->helper('catalog/output');
    $specification = $_product->getspecifications();
    $applications = $_product->getapplications();
    $fullapplication = $_product->getviewourfullapplication();
    $supportmaterials = $_product->getsupportmaterials();
    $faq = $_product->getfaq();


foreach ($_product->getRelatedLinkCollection() as $link) {
        $relatedData[$link->getLinkedProductId()]['position'] = $link->getPosition();
        $itsProducts[] = $link->getLinkedProductId();
		}
		
    $related = $itsProducts;

?>
<div class="info-wrapper">
    <nav class="add-nav">
    		<div class="container">
    			<ul>
                    <li class="green active"><a href="#order"><?php echo $this->__('General Info'); ?><em></em></a></li>
    					<?php if(!empty($specification)):  ?>
    							<li class="blue"><a href="#specifications"><?php echo $this->__('Specifications'); ?><em></em></a></li>
    					<?php endif; ?>
    					<?php if(count($related)):  ?>
    							<li class="yellow"><a href="#accessories"><?php echo $this->__('Accessories'); ?><em></em></a></li>
	                    <?php endif; ?>
    					<?php if(!empty($applications)):  ?>
    							<li class="light-blue"><a href="#applications"><?php echo $this->__('Applications'); ?><em></em></a></li>
    					<?php endif; ?>
    					<?php if(!empty($fullapplication)):  ?>
    							<li class="blue"><a href="#fullapplication"><?php echo $this->__('Video'); ?><em></em></a></li>
    					<?php endif; ?>
    					<?php if(!empty($supportmaterials)):  ?>
    							<li class="yellow"><a href="#support-materials"><?php echo $this->__('Literature'); ?><em></em></a></li>
    					<?php endif; ?>
    					<?php if(!empty($faq)):  ?>
    							<li class="light-blue"><a href="#faq"><?php echo $this->__('Success Stories'); ?><em></em></a></li>
    					<?php endif; ?>
    			</ul>
    		</div>
    </nav>

   <div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>

    <?php if(!empty($specification)) : ?>
        <div id="specifications" class="main-tab container">
            <div class="sub-title">
                <h1><?php echo $this->__('Specifications'); ?></h1>
            </div>
            <div class="box-collateral box-description">
                <?php echo $_helper->productAttribute($_product, $specification, 'specifications') ?>
            </div>
        </div>
    <?php endif; ?>

<!--Related Products-->
    <?php if($this->getChildHtml('related') != ''){ ?>
    <div id="accessories" class="main-tab container">
            <div class="sub-title">
                <h1><?php echo $this->__('Accessories'); ?></h1>
                <?php echo $this->getChildHtml('related');?>
            <?php include "related.php"; ?>
             </div> 
     </div>
     <?php } ?>
     
<!-- Related Products-->

 

<!-- video -->
    <?php if(!empty($fullapplication)) : ?>
        <div id="fullapplication" class="main-tab container">
            <div class="sub-title">
                <h1><?php echo $this->__('Video'); ?></h1>
            </div>
          <section class="materials-box">
                <?php echo $_helper->productAttribute($_product, $fullapplication, 'fullapplication') ?>
            </section>
        </div>
    <?php endif; ?>
<!-- end video-->
    <?php if(!empty($applications)) : ?>
        <div id="applications" class="main-tab container">
            <div class="sub-title">
                <h1><?php echo $this->__('Applications'); ?></h1>
               
            </div>
            <section class="materials-box">
                <?php echo $_helper->productAttribute($_product, $applications, 'applications') ?>
            </section>
        </div>
    <?php endif; ?>
    <?php if(!empty($supportmaterials)) : ?>
        <div id="support-materials" class="main-tab container">
            <div class="sub-title">
                <h1><?php echo $this->__('Literature'); ?></h1>
            </div>
            <section class="materials-box">
                <?php echo $_helper->productAttribute($_product, $supportmaterials, 'supportmaterials') ?>
            </section>
        </div>
    <?php endif; ?>
    <?php if(!empty($faq)) : ?>
        <div id="faq" class="main-tab container">
            <div class="sub-title">
                <h1><?php echo $this->__('Success Stories'); ?></h1>
            </div>
            <section class="materials-box question">
                <?php echo $_helper->productAttribute($_product, $faq, 'faq') ?>
            </section>
        </div>
    <?php endif; ?>
     
     <div id="order" class="main-tab container">
        <div class="main-column materials-box">
        
    	    <div id="description" class="main-tab container">
    			<?php echo $_product->getDescription(); ?>
    	    </div>
            
            <?php echo $this->getChildHtml('product_additional_data') ?>
        </div>  
        <aside class="col-right sidebar">
            <!-- Order form use to be here: not needed -->
            <?php// echo $this->getChildHtml('related');?>
            <?php// include "tmp_related.php"; ?>
   <!--Start Static Block -->
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('get_help')->toHtml() ?>
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('news_events')->toHtml() ?> 
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('constant_contact')->toHtml() ?> 
                <!--End Static Block-->
       
        
        </aside>
    </div>
</div>