<?php if(count($this->getItemCollection()->getItems())): ?>
<div class="box-collateral box-up-sell">
    <div class="sub-title">
      <h1><?php echo $this->__('Configure and Order'); ?></h1>
    </div>
    <div class="configure-box">
        <?php $this->resetItemsIterator() ?>
        <?php $counter = 0; for($_i=0;$_i<$this->getRowCount();$_i++): ?>
            <?php for($_j=0;$_j<$this->getColumnCount();$_j++): ?>
                <?php if($_link=$this->getIterableItem()): ++$counter; ?>
                <section class="row">
                    <a href="<?php echo $_link->getProductUrl() ?>" data-sku="<?php echo $_link->getSku() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>" class="product-image <?php if($counter%2 == 0){ echo 'blue';} if($counter%3 == 0){ echo 'green'; } ?>"><img src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image')->resize(174,174) ?>" width="174" height="174" alt="<?php echo $this->htmlEscape($_link->getName()) ?>" /></a>
                    <div class="txt">
                        <h2 class="product-name"><a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>"><?php echo $this->htmlEscape($_link->getName()) ?></a></h2>
                        
                        
                        <?php $shortdescription = $_link->getShortDescription(); if(!empty($shortdescription)): ?>
                        <div class="short-description">
                            <div class="std">
                                <?php echo $shortdescription; ?>
                            </div>
                        </div>
                        <?php endif; ?>
                    </div>
                </section>
                <?php endif; ?>
            <?php endfor; ?>
        <?php endfor; ?>
    </div>
</div>
<?php endif ?>