<!DOCTYPE html>
<html lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<div id="wrapper">
    <?php echo $this->getChildHtml('global_notices') ?>
    <div class="page">
    <?php echo $this->getChildHtml('header') ?>
        <?php
            $currenturl = $this->helper('core/url')->getCurrentUrl();
            $currentcategory = Mage::registry('current_category');
            $identifier = Mage::getSingleton('cms/page')->getIdentifier();
            $currentproduct = Mage::registry('current_product');
        ?>
        <div id="main" class="main-container col1-layout">
            <?php echo $this->getChildHtml('breadcrumbs') ?>
            <?php echo $this->getChildHtml('page_title') ?>
            <?php if($identifier != 'home' && empty($currentcategory) && empty($currentproduct) && strpos($currenturl,'catalogsearch/advanced/result') == false): ?>
            <div class="container main">
                <div class="col-main">
            <?php endif; ?>
                <?php echo $this->getChildHtml('global_messages') ?>
                <?php echo $this->getChildHtml('content') ?>
            <?php if($identifier != 'home' && empty($currentcategory) && empty($currentproduct) && strpos($currenturl,'catalogsearch/advanced/result') == false): ?>
                </div>
            </div>
            <?php endif; ?>
        </div>
    </div>
</div>
<?php echo $this->getChildHtml('footer') ?>
<?php echo $this->getChildHtml('before_body_end') ?>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
