<?php
$_productCollection=$this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');

$currentCountry = Mage::getModel('core/session')->getData('current_country');
$countryCode = $currentCountry['code'];


if(in_array($countryCode, array('US','CA'))){
    $showPrice = true;
}else{
    $showPrice = false;
}


?>
<?php if(!$_productCollection->count()): ?>
	<?php 
		$category = Mage::registry('current_category');
		$currentCatId = $category->getId();
		$childrenCategories = '';
		$childrenCategories = Mage::getModel('catalog/category')->load($currentCatId)->getChildrenCategories();
   ?>
	<?php if (!empty($childrenCategories)): ?>
		<div class="container category-product-list grid-view categories">
			<?php 
			$i=0;
			//$catAsArray = explode(',', $childrenCategories);
			foreach ($childrenCategories as $cat): ?>
				<?php 
					$category = Mage::getModel('catalog/category')->load($cat->getId()); 
					$imageUrl = $category->getThumbnail();
					if (empty($imageUrl)) {
						$imageUrl = 'gray-image.jpg';
					}
				?>
					<?php if (($i % 3) == 0): ?><div class="row"><?php endif; ?>
						<div class="col-lg-4 product">
							<div class="view view-1">
								<h2 class="product-name"><a href="<?php echo $category->getUrl(); ?>"><?php echo $category->getName(); ?></a></h2>
								<a href="<?php echo $category->getUrl(); ?>" class="img cat-link">
									<img src="<?php echo '/media/catalog/category/'.$imageUrl; ?>" class="category-image" width="150" height="127">
								</a>
								<div class="cta-buttons">
									<a href="<?php echo $category->getUrl(); ?>" class="action-button">View Products</a> 
									<a href="#" id="quick-info" class="action-button">Quick Info</a>
								</div>
							</div>
							<div class="view view-2">
								<h4 class="quick-info-heading">QUICK INFO<span class="close">x</span></h4>
								<?php $smalldescription = $category->getDescription(); if(!empty($smalldescription)):
									$smalldescription = $category->getDescription();
									$smalldescription = trim($smalldescription);
									$limit = 250;
									if (strlen($smalldescription) > $limit) {
										$smalldescription = substr($smalldescription, 0, strrpos(substr($smalldescription, 0, $limit), ' '));
										$smalldescription = $smalldescription.'...';
									} ?>
									<div class="short-description">
										<div class="std">
											<meta itemprop="description" content="<?php echo $smalldescription; ?>">
											<p><?php echo $smalldescription; ?></p>
										</div>
									</div>
								<?php endif; ?>					
							</div>	
						</div>	                        	                
					<?php if (($i % 3) == 2): ?></div><?php endif; $i++; ?>                 	
			<?php endforeach; ?>
		</div>
	<?php else: ?>
    	<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
    <?php endif; ?>
<?php else: ?>
    <?php $routeName = Mage::app()->getRequest()->getRouteName(); if($routeName == 'catalogsearch'): ?>
        <?php echo $this->getToolbarHtml() ?>
    <?php endif; ?>

    <div class="col-main">
        <?php $_collectionSize = $_productCollection->count() ?>
        <?php $_columnCount = $this->getcolumnscount();  if(empty($_columnCount)) { $_columnCount = 3;} ?>
        <div class="container category-product-list grid-view">
            <?php $i=0; foreach ($_productCollection as $_product): ?>
            	<?php if (($i % 3) == 0): ?><div class="row"><?php endif; ?>
                <div class="col-lg-4 product" itemscope itemtype="http://schema.org/Product">
                	<div class="view view-1">
						<h2 class="product-name" itemprop="name"><a href="<?php echo $_product->getProductUrl() ?>" data-sku="<?php echo $_product->getSku() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
						<a itemprop="url" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" data-sku="<?php echo $_product->getSku() ?>" class="img">
							<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(150,127); ?>" width="150" height="127" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />

						</a>
						<p class="product-sku">
							<?php echo 'SKU: '.$_product->getSku() ?>
						</p>
						<?php if($_product->_data['price'] != 0): ?>
							<span itemprop="offers" itemscope itemtype="http://schema.org/Offer">
								<meta itemprop="priceCurrency" content="USD"/>
								<meta itemprop="price" content="<?php echo $_product->getFinalPrice() ?>" />
								<meta itemprop="itemCondition" href="http://schema.org/NewCondition" content="New" />
							</span>
							<div class="price-wrapper">
								Price: <span>$<?php echo number_format($_product->getFinalPrice(),2) ?></span>
							</div>
						<?php else: ?>
							<div class="price-wrapper">
								&nbsp;
							</div>						
						<?php endif; ?>
						<div class="cta-buttons">
							<a href="<?php echo $_product->getProductUrl() ?>" class="action-button">View Product</a> 
							<a href="#" id="quick-info" class="action-button">Quick Info</a>
						</div>
					</div>
					<div class="view view-2">
						<h4 class="quick-info-heading">QUICK INFO<span class="close">x</span></h4>
						<span itemscope itemtype="http://schema.org/Brand" style="display:none;">
							<span itemprop="name">Omni International "The Homogenizer Company"</span>
						</span>
						<span style="display:none;">Model: 
							<span itemprop="model"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></span>
						</span>
						<?php $smalldescription = $_product->getsmalldescription(); if(!empty($smalldescription)):
							$smalldescription = $_product->getsmalldescription();
							$smalldescription = trim($smalldescription);
							$limit = 250;
							if (strlen($smalldescription) > $limit) {
								$smalldescription = substr($smalldescription, 0, strrpos(substr($smalldescription, 0, $limit), ' '));
								$smalldescription = $smalldescription.'...';
							} ?>

							<div class="short-description">
								<div class="std">
									<meta itemprop="description" content="<?php echo $smalldescription; ?>">
									<p><?php echo $smalldescription; ?></p>
								</div>
							</div>
						<?php endif; ?>					
					</div>				
                </div>
            	<?php if (($i % 3) == 2): ?></div><?php endif; $i++; ?>
            <?php endforeach ?>
        </div>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    </div>
<?php endif; ?>
<script>
(function($){
$(document).ready(function(){
	$(document).on('click','.category-product-list #quick-info', function(e) {
		e.preventDefault();
		$(this).parents('.product').find('.view-2').addClass('active');
	});
	$(document).on('click','.category-product-list .close', function() {
		$(this).parents('.product').find('.view-2').removeClass('active');
	});
});
})(jQuery);
</script>
