<!DOCTYPE html>
<html lang="<?php echo $this->getLang() ?>">
<head>
    <?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<div id="wrapper">
    <?php echo $this->getChildHtml('global_notices') ?>
    <div class="page">
        <?php echo $this->getChildHtml('header') ?>
        <div id="main" class="main-container col2-left-layout">
            <?php echo $this->getChildHtml('breadcrumbs') ?>
            <?php echo $this->getChildHtml('page_title') ?>
            <div class="main">
                <div class="application-header-image">
                    <img src="https://www.omni-inc.com/skin/frontend/default/omnicom/images/Protocol-Database-banner-OLD-GREEN.jpg" alt="Omni's Protocol Database header image">
                </div>
                
                <form action="" name="application-search" id="application-search-form">
                    <!-- 
                    Emulsion Icon: Created by Evan MacDonald
                    Human Icon: Created by Lemon Liu
                    Cell Icon: Created by Sergey Demushkin
                    Plant Icon: Created by Pham Thi Dieu Linh
                    Animal Icon: Created by Francisca Arévalo
                    Calendar Icon: Created by Joris Hoogendoorn
                    Pdf Icon: Created by Graham Dragonborn Wilsdon 
                    -->
                    <div class="col-left sidebar"><?php echo $this->getChildHtml('left') ?></div>
                    <div class="col-main">
                        <?php echo $this->getChildHtml('global_messages') ?>
                        <?php echo $this->getChildHtml('content') ?>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<?php echo $this->getChildHtml('footer') ?>
<?php echo $this->getChildHtml('before_body_end') ?>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
