<?php $document = $this->getDocument(); ?>
<?php $products = $this->getProductCollection(); ?>

<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="application-header-image">
    <img src="https://www.omni-inc.com/skin/frontend/default/omnicom/images/protocol/protocol-database-header-2.jpg" alt="Omni's Protocol Database header image">
</div>
<div id="nav-block">
    <a href="/protocol/application#application-search-form" class="back col">
      <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
   viewBox="0 0 11.1 19.4" style="enable-background:new 0 0 11.1 19.4;" xml:space="preserve">
        <style type="text/css">
          .st0{fill:#FFFFFF;}
        </style>
        <g>
          <g transform="translate(-237.000000, -335.000000)">
            <path class="st0" d="M246.7,354.4l-9.7-9.7l9.7-9.7l1.4,1.4l-8.3,8.3l8.3,8.3L246.7,354.4"/>
          </g>
        </g>
      </svg>

        <span>Back to search</span>
    </a>
    <a href="/contacts/" class="contact-us col">
        <span class='large'>Have Questions? Contact our sales team for assistance.</span>
        <span class='small'>Contact Us</span>
    </a>
    
</div>
<!-- END OF NAV-BLOCK -->
<div class="app-database">
    <div class="header">
        <div class="left-header-info">
            <div class="inner-wrapper">
                <?php $appTitle = htmlspecialchars_decode($document->getName()); ?>
                <h1>Title:<span class="title"><?php echo $appTitle; ?></span></h1>
                <p>Sample amount: <span><?php echo $document->getSampleAmount(); ?></span></p>
            </div>
        </div>
        <div class="right-header-info">
        <div class="inner-wrapper">
            <div class="sample-type <?php echo strtolower($document->getSampleType()->getName()); ?>">
                <?php echo $document->getSampleType()->getName(); ?>
            </div>
            <?php $files = $document->getFiles(); ?>
            <?php if($files->getSize()): ?>
                <div class="pdf">
                  <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" fill="#ffffff" x="0px" y="0px" viewBox="0 0 76.5 89" style="enable-background:new 0 0 76.5 89;" xml:space="preserve">
                    <g>
                      <g>
                        <path d="M20.6,38.5h-1.5V43h1.4c1.9,0,2.8-0.8,2.8-2.3S22.4,38.5,20.6,38.5z"/>
                        <path d="M0,0v89h76.5V28.5L47.9,0H0z M20.7,46.9h-1.4v4.6h-5.4V34.4H21c4.9,0,7.7,2.5,7.7,6.2C28.7,44.7,25.9,46.9,20.7,46.9z
                           M37.8,51.6H31V34.4h7.1c6.2,0,9.7,3.4,9.7,8.5C47.9,48.1,44.3,51.6,37.8,51.6z M50.3,34.4h13.2v4.3h-7.8v2.5h6.1v4.3h-6.1v6.1
                          h-5.3L50.3,34.4L50.3,34.4z"/>
                        <path d="M37.8,38.5h-1.3v8.9h1.6c2.7,0,4.3-1.3,4.3-4.4C42.4,39.8,41,38.5,37.8,38.5z"/>
                      </g>
                    </g>
                  </svg>
              </div>
            <?php endif; ?>
        </div>
        </div><!-- END OF right-header-info -->
    </div>
    <!-- END OF HEADER -->
    <div class="col-wrap">
        <div class="left-col col">
      <div class="inner-wrap">
        <h2>Application Info</h2>
        <?php $files = $document->getFiles(); ?>
        <?php if($files->getSize()): ?>
          <?php if(Mage::getSingleton('customer/session')->isLoggedIn()): ?>
            <?php if(!$this->isAllowToDownload()): ?>
              <p>Exceed download limit per day.</p>
            <?php else: ?>
            <?php $files = $document->getFiles(); ?>
                <ul>
                    <?php foreach($files as $file): ?>
                        <li>
                            <div class="download-pdf">
                                <a class="button btn-pdf application_download_link goodToDownload" 
                                    href="javascript:void(0)" 
                                    data-url="<?php echo $this->getDownloadLink($file) ?>"
                                    title="<?php echo $file->getName() ?>"
                                    target="_blank">
                                    <span>Download PDF</span>
                                    <div class="icon">
                                      <svg version="1.1" 
                                        id="Layer_1" xmlns="http://www.w3.org/2000/svg" 
                                        xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 90 90" style="enable-background:new 0 0 90 90;" xml:space="preserve">
                                          <style type="text/css">
                                            .st0{fill:#FFFFFF;}
                                          </style>
                                          <g>
                                              <path class="st0" d="M15.5,38.4c0.3-0.1,0.5-0.3,0.6-0.5c0.1-0.2,0.2-0.4,0.2-0.7c0-0.3-0.1-0.6-0.3-0.8c-0.2-0.2-0.5-0.4-0.8-0.4
                                          c-0.2,0-0.8-0.1-2.2-0.1h-0.7v2.6h1C14.9,38.5,15.4,38.4,15.5,38.4z"/>
                                              <path class="st0" d="M29.1,43.9c1.1,0,2-0.3,2.6-1c0.7-0.7,1-1.8,1-3.2c0-1.3-0.3-2.3-0.9-2.9c-0.6-0.6-1.4-0.9-2.4-0.9
                                          c-0.2,0-0.4,0-0.6,0v8C28.9,43.9,29,43.9,29.1,43.9C29.1,43.9,29.1,43.9,29.1,43.9z"/>
                                              <path class="st0" d="M1.8,54H13l0,34.6c0,0.8,0.6,1.4,1.4,1.4H55v-3.6H17.1c-0.3,0-0.5-0.2-0.5-0.5V54h41.1c1,0,1.7-0.8,1.7-1.7
                                          V27.6c0-1-0.8-1.7-1.7-1.7H16.6V4.1c0-0.3,0.2-0.5,0.5-0.5h40.9c0.3,0,0.5,0.2,0.5,0.5l0,12.5c0,0.8,0.6,1.4,1.4,1.4h12.6
                                          c0.3,0,0.5,0.2,0.5,0.5v23.7c0,0.1,0,0.1,0,0.2h3.5c0-0.1,0-0.1,0-0.2l0-26.6c0-0.4-0.2-0.9-0.5-1.2l-14-14C62,0.2,61.4,0,61,0
                                          H14.4C13.6,0,13,0.6,13,1.4v24.4H1.7c-1,0-1.7,0.8-1.7,1.7l0,24.6C0,53.2,0.8,54,1.8,54z M40.5,32h11.7V36h-6.9v2.1h6.2v3.7h-6.2
                                          v6.1h-4.8V32z M24.2,32.3l0.6-0.1c1.1-0.2,2.7-0.3,4.2-0.3c2.6,0,4.4,0.5,5.8,1.7c1.6,1.3,2.5,3.4,2.5,6c0,3.4-1.3,5.3-2.4,6.3
                                          c-1.5,1.4-3.7,2-6.6,2c-1.3,0-2.5-0.1-3.6-0.2l-0.7-0.1L24.2,32.3L24.2,32.3z M7.3,32h6.1c2,0,3.4,0.1,4,0.2c1.1,0.2,2,0.8,2.7,1.7
                                          c0.7,0.8,1.1,1.9,1.1,3.2c0,1-0.2,1.9-0.6,2.6c-0.4,0.7-0.9,1.3-1.6,1.7c-0.6,0.4-1.3,0.7-1.9,0.8c-0.8,0.2-2,0.2-3.5,0.2h-1.3v5.4
                                          h-5L7.3,32L7.3,32z"/>
                                              <path class="st0" d="M89.1,71.2h-8.9V54.9c0-0.5-0.4-0.9-0.9-0.9h-8.7c-0.5,0-0.9,0.4-0.9,0.9v16.4h-8.9c-0.3,0-0.6,0.2-0.8,0.4
                                          c-0.2,0.3-0.2,0.6,0,0.9l14.1,17c0.2,0.3,0.4,0.4,0.8,0.4c0.3,0,0.6-0.2,0.8-0.4l14.1-17c0.2-0.3,0.2-0.6,0-0.9
                                          C89.7,71.4,89.4,71.2,89.1,71.2z"/>
                                          </g>
                                      </svg>
                                    </div>
                                </a>
                            </div>
                        </li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
            <?php else: ?>
              <div class="download-pdf open-forms">
                <div style="cursor: pointer;" class="icon">
                    <a class="button btn-pdf application_download_link" href="javascript:void(0)" target="_blank">
                    <span>Download PDF</span>
                    <div class="icon">
                        <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 90 90" style="enable-background:new 0 0 90 90;" xml:space="preserve">
                            <style type="text/css">
                                .st0{fill:#FFFFFF;}
                            </style>
                            <g>
                                <path class="st0" d="M15.5,38.4c0.3-0.1,0.5-0.3,0.6-0.5c0.1-0.2,0.2-0.4,0.2-0.7c0-0.3-0.1-0.6-0.3-0.8c-0.2-0.2-0.5-0.4-0.8-0.4
                            c-0.2,0-0.8-0.1-2.2-0.1h-0.7v2.6h1C14.9,38.5,15.4,38.4,15.5,38.4z"/>
                                <path class="st0" d="M29.1,43.9c1.1,0,2-0.3,2.6-1c0.7-0.7,1-1.8,1-3.2c0-1.3-0.3-2.3-0.9-2.9c-0.6-0.6-1.4-0.9-2.4-0.9
                            c-0.2,0-0.4,0-0.6,0v8C28.9,43.9,29,43.9,29.1,43.9C29.1,43.9,29.1,43.9,29.1,43.9z"/>
                                <path class="st0" d="M1.8,54H13l0,34.6c0,0.8,0.6,1.4,1.4,1.4H55v-3.6H17.1c-0.3,0-0.5-0.2-0.5-0.5V54h41.1c1,0,1.7-0.8,1.7-1.7
                            V27.6c0-1-0.8-1.7-1.7-1.7H16.6V4.1c0-0.3,0.2-0.5,0.5-0.5h40.9c0.3,0,0.5,0.2,0.5,0.5l0,12.5c0,0.8,0.6,1.4,1.4,1.4h12.6
                            c0.3,0,0.5,0.2,0.5,0.5v23.7c0,0.1,0,0.1,0,0.2h3.5c0-0.1,0-0.1,0-0.2l0-26.6c0-0.4-0.2-0.9-0.5-1.2l-14-14C62,0.2,61.4,0,61,0
                            H14.4C13.6,0,13,0.6,13,1.4v24.4H1.7c-1,0-1.7,0.8-1.7,1.7l0,24.6C0,53.2,0.8,54,1.8,54z M40.5,32h11.7V36h-6.9v2.1h6.2v3.7h-6.2
                            v6.1h-4.8V32z M24.2,32.3l0.6-0.1c1.1-0.2,2.7-0.3,4.2-0.3c2.6,0,4.4,0.5,5.8,1.7c1.6,1.3,2.5,3.4,2.5,6c0,3.4-1.3,5.3-2.4,6.3
                            c-1.5,1.4-3.7,2-6.6,2c-1.3,0-2.5-0.1-3.6-0.2l-0.7-0.1L24.2,32.3L24.2,32.3z M7.3,32h6.1c2,0,3.4,0.1,4,0.2c1.1,0.2,2,0.8,2.7,1.7
                            c0.7,0.8,1.1,1.9,1.1,3.2c0,1-0.2,1.9-0.6,2.6c-0.4,0.7-0.9,1.3-1.6,1.7c-0.6,0.4-1.3,0.7-1.9,0.8c-0.8,0.2-2,0.2-3.5,0.2h-1.3v5.4
                            h-5L7.3,32L7.3,32z"/>
                                <path class="st0" d="M89.1,71.2h-8.9V54.9c0-0.5-0.4-0.9-0.9-0.9h-8.7c-0.5,0-0.9,0.4-0.9,0.9v16.4h-8.9c-0.3,0-0.6,0.2-0.8,0.4
                            c-0.2,0.3-0.2,0.6,0,0.9l14.1,17c0.2,0.3,0.4,0.4,0.8,0.4c0.3,0,0.6-0.2,0.8-0.4l14.1-17c0.2-0.3,0.2-0.6,0-0.9
                            C89.7,71.4,89.4,71.2,89.1,71.2z"/>
                            </g>
                        </svg>
                    </div>
                </a>
                </div>
              </div>
            <?php endif; ?>
        <?php endif; ?>

        <?php $description = $document->getProcedure(); ?>
        <?php if($description): ?>
        <div class="description">
            <h3>Procedure:</h3>
            <?php $appDesc = htmlspecialchars_decode($document->getProcedure()); ?>
            <p><?php echo $appDesc; ?></p>
        </div>
        <?php endif; ?>
        <?php $goal = $document->getAnalyte(); ?>
        <?php if($goal): ?>
        <div class="goal">
          <h3>Analyte:</h3>
          <p>
            <?php echo $goal; ?>
          </p>
        </div>
        <?php endif; ?>
        <?php if ($document->getImage()): ?>
        <div class="image">
            <img src="<?php echo $document->getImage(); ?>" alt="<?php echo $document->getName(); ?>">
        </div>
        <?php endif; ?>
        <div class="scope-info">
            <div class="sample">
                <h4>Sample Type:</h4>
                <span><?php echo $document->getSampleType()->getName(); ?></span>
            </div>
            <div class="tags">
                <h4>Tags:</h4>
                <?php $tags = $document->getTags(); ?>
                <ul>
                    <?php foreach($tags as $tag): ?>
                    <li><?php echo $tag->getName() ?></li>
                    <?php endforeach; ?>
                </ul>
            </div>
            <div class="created"><h4>Created On:</h4>
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                   viewBox="0 0 71.2 79" style="enable-background:new 0 0 71.2 79; fill: #5e5e5e;" xml:space="preserve">
                <path d="M63.3,11.7h-3.6v13.9H47.1V11.7h-23v13.9H11.5V11.7H7.9c-4.4,0-7.9,3.6-7.9,7.9v51.5C0,75.5,3.6,79,7.9,79h55.4
                  c4.4,0,7.9-3.6,7.9-7.9V19.6C71.2,15.2,67.6,11.7,63.3,11.7z M63.3,71.1H7.9V32.4h55.4V71.1z M14.2,18.7V3.5c0-1.9,1.5-3.5,3.5-3.5
                  s3.5,1.5,3.5,3.5v15.2c0,1.9-1.5,3.5-3.5,3.5S14.2,20.6,14.2,18.7z M50.1,18.7V3.5c0-1.9,1.5-3.5,3.5-3.5s3.5,1.5,3.5,3.5v15.2
                  c0,1.9-1.5,3.5-3.5,3.5S50.1,20.6,50.1,18.7z"/>
                </svg>
                <p><?php echo date('Y-m-d', strtotime($document->getCreatedAt())); ?></p>
            </div>
        </div>
    </div>
    </div>
    <!-- END OF LEFT-COL -->
    <div class="right-col col">
      <div class="inner-wrap">
        <h2>Product used</h2>
        <div class="application-upsell">
            <?php echo $this->getChildHtml('application_view_upsell'); ?>
        </div>
      </div>
    </div>
    <!-- END OF RIGHT-COL -->
    <div class="download-form">
      <span class="close-pdf">&times;</span>
      <div class="inner-wrap">
        <h3>To download this PDF, you must be logged into your Omni account.</h3>
        <div class="no-account">
          <p>Don't have an account?</p>
          <button class="createAccount-btn btn" type="button">Click here to create an account</button>
        </div>
        <div class="have-account">
          <p>Already have an account?</p>
          <button class="haveAccount-btn" type="button">Click here to login in now</button>
        </div>
        <form id="app-pdf-download" method="post"
              action="<?php echo $this->getUrl('application/application/login') ?>">
          <div class="input-group">
            <label for="first-name">First Name</label>
            <input type="text" name="customer_data[first_name]" placeholder="First Name" required />
          </div>
          <div class="input-group">
            <label for="last-name">Last Name</label>
            <input type="text" name="customer_data[last_name]" placeholder="Last Name" required />
          </div>
          <div class="input-group">
            <label for="company">Company</label>
            <input type="text" name="customer_data[company]" placeholder="Company" required />
          </div>
          <div class="input-group">
            <label for="phone">Phone</label>
            <input type="text" name="customer_data[phone]" placeholder="Phone" required />
          </div>
          <div class="input-group">
            <label for="email">Email</label>
            <input type="text" name="customer_data[email]" placeholder="Email" required />
          </div>
            <div class="input-group">
                <label for="email">Password</label>
                <input type="password" name="customer_data[password]" placeholder="Password" required />
            </div>
          <div class="input-group submit">
            <button href="#" class="button btn">Submit</button>
          </div>
        </form>
        <form id="app-pdf-download-login" method="post"
              action="<?php echo $this->getUrl('application/application/login') ?>">
              <div class="input-group">
                  <label for="email">Email</label>
                  <input type="text" name="customer_data[email]" placeholder="Email" required />
                  <input type="hidden" name="customer_data[login]" value="1">
              </div>
              <div class="input-group">
                  <label for="email">Password</label>
                  <input type="password" name="customer_data[password]" placeholder="Password" required />
              </div>
              <div class="input-group submit">
                  <button href="#" class="button btn">Login</button>
              </div>
        </form>
        <script type="text/javascript">
            //< ![CDATA[
            var customForm = new VarienForm('register-form');
            //]]>
        </script>
      </div>
    </div>
    <div class="overlay-bg"></div>
  </div>
  <!-- END OF COL-WRAP -->
</div>
<!-- END OF APP-DATABASE -->
<script type="text/javascript">

    jQuery(function ($) {

      var createAccount = $('#app-pdf-download');
      var haveAccount = $('#app-pdf-download-login');
      var createAccountBtn = $('.no-account');
      var haveAccountBtn = $('.have-account');
      var overlay = $('.overlay-bg');

      createAccount.addClass('hidden');
      haveAccountBtn.addClass('hidden');

      createAccountBtn.find('.createAccount-btn').on('click', function(e){
        e.preventDefault();
        console.log('createAccount');
        haveAccountBtn.removeClass('hidden');
        createAccountBtn.addClass('hidden');
        createAccount.removeClass('hidden');
        if(!haveAccount.hasClass('hidden')){
          haveAccount.addClass('hidden');
        }
      });

      haveAccountBtn.find('.haveAccount-btn').on('click', function(e){
        e.preventDefault();
        console.log('haveAccount');
        haveAccountBtn.addClass('hidden');
        createAccountBtn.removeClass('hidden');
        haveAccount.removeClass('hidden');
        if(!createAccount.hasClass('hidden')){
          createAccount.addClass('hidden');
        }
      });





        $('.application_download_link').click(function(e){
            e.preventDefault();
            var get_url = '<?php echo $this->getCustomerLogUrl(); ?>',
                get_data = {application: '<?php echo $document->getId(); ?>'},
                downloadUrl = $(this).data('url');

            $.ajax({
                type: 'GET',
                url: get_url,
                data: get_data,
                success: function (data) {
                    data = $.parseJSON(data);
                    if(data.success){
                        window.location.replace(downloadUrl);
                    }
                    console.log(data);
                    //console.log(data);
                }, error: function (xhr, ajaxOptions, thrownError) {
                    console.log(xhr.responseText);
                    console.log(thrownError);
                }
            });
        });
        var readmore = $('.read-more');
        readmore.on('click', function(event){
            $(this).parent().css({maxHeight: '100%'});
            $(this).fadeOut('fast');
        });


        if($('.download-pdf.open-forms').length){
            $('.download-pdf.open-forms').click(function(){
                if($('.download-form').hasClass('open')){
                    $('.download-form').removeClass('open');
                } else{
                    $('.download-form').addClass('open');
                    overlay.addClass('show');
                }
            });
        }

        $('.close-pdf').on('click', function(event){
            $('.overlay-bg').removeClass('show');
           $('.download-form').removeClass('open');
        });
    });
</script>