<?php
/**
 *
 * CART2QUOTE CONFIDENTIAL
 * __________________
 *
 *  [2009] - [2016] Cart2Quote B.V.
 *  All Rights Reserved.
 *
 * NOTICE OF LICENSE
 *
 * All information contained herein is, and remains
 * the property of Cart2Quote B.V. and its suppliers,
 * if any.  The intellectual and technical concepts contained
 * herein are proprietary to Cart2Quote B.V.
 * and its suppliers and may be covered by European and Foreign Patents,
 * patents in process, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Cart2Quote B.V.
 *
 * @category    Ophirah
 * @package     Qquoteadv
 * @copyright   Copyright (c) 2016 Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */
?>
<?php /** @var $this Ophirah_Qquoteadv_Block_Qquote */ ?>

<div class="sales-page-title page-title">
	<h1><?php echo $this->__('Request for Quote') ?></h1>
</div>

<?php if ($this->getQuote()->getData() == array()): ?>
<div class="cart-empty">
	<p><?php echo $this->__('No Items to display.'); ?></p>
	<p><?php echo Mage::helper('checkout')->__('Click <a href="%s">here</a> to continue shopping.', $this->getUrl()) ?></p>
</div>
<?php else: ?>
    <?php $productNames = $this->getNotSalableProductNames($this->getQuote());  ?>
    <?php if($this->displayAssignedTo()): ?>
        <div class="assigned-to">
            <?php if(Mage::helper('qquoteadv')->getAdminUser() !== null): ?>
                <?php if($this->isAssignPreviousEnabled()): ?>
                    <?php if($this->helper('customer')->isLoggedIn()): ?>
                        <?php
                        $customerData = Mage::getSingleton('customer/session')->getCustomer();
                        echo $this->__('Quote will be assigned to <strong>%s</strong>', Mage::helper('qquoteadv')->getAdminUser(Mage::helper('qquoteadv')->getPreviousAssignedAdmin(null, $customerData->getId()))->getName()); ?>
                     <?php else: ?>
                        <?php echo $this->__('If the end user has no previous assigned sales representative the quote will be assigned to <strong>%s</strong>.', $this->getAdminUser()->getName()); ?>
                    <?php endif; ?>
                <?php else: ?>
                    <?php echo $this->__('Quote will be assigned to <strong>%s</strong>', $this->getAdminUser()->getName()); ?>
                <?php endif; ?>
            <?php endif; ?>
        </div>
    <?php endif; ?>
    <?php echo $this->getMessagesBlock()->toHtml() ?>
	<div class="container">
		<div class="row">
			<div class="col-lg-12 pull-left padding-0">
				<form method="post" id="quotelist" name="quotelist" action='<?php echo $this->getUrl('qquoteadv/index/quoteRequest', array('_secure' => Mage::app()->getStore()->isCurrentlySecure())) ?>'>
					<?php if ($this->displayAssignedTo() && $this->getAdminUser() !== null): ?>
						<input type="hidden" name="user_id" value="<?php echo $this->getAdminUser()->getId(); ?>"/>
					<?php endif; ?>
					<table cellspacing="0" border="0" id="shopping-cart-table" class="data-table cart-table">
						<colgroup>
							<col width="280"/>
							<col />
							<col width="1"/>
							<col />
							<col />
						</colgroup>
						<thead>
						<tr>
							<th class="text-left"><?php echo Mage::helper('sales')->__('Items in Your Cart') ?></th>					
							<th class="text-left"><?php echo Mage::helper('checkout')->__('Price') ?></th>
							<th class="text-left"><?php echo Mage::helper('sales')->__('Qty') ?></th>
							<th></th>
							<th class="text-right"><?php echo Mage::helper('sales')->__('Item Subtotal') ?></th>					
						</tr>
						</thead>
						<tbody>
						<?php $i = 0; $quoteSubtotal = 0; foreach ($this->getQuote() as $item): ?>
						<?php
							$product = $this->getProduct($item->getProductId());
							$quoteByProduct = Mage::helper('qquoteadv')->getQuoteItem($product, $item->getAttribute(), null, $item);
							$qty = $quoteByProduct->getItemsQty(); $finalPrice = 0;
							if (Mage::getStoreConfig('tax/cart_display/price') == 2) {
								$finalPrice = $quoteByProduct->getGrandTotal() / ($qty > 0 ? $qty : 1);
							} else {
								$finalPrice = $quoteByProduct->getSubtotal() / ($qty > 0 ? $qty : 1);
							}
							if ($product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_CONFIGURABLE) {
								$childProduct = Mage::getModel('qquoteadv/qqadvproduct')->getConfChildProduct($item->getId());
							} else {
								$childProduct = $product;
							}
						?>
						<tr class="product">
							<td class="text-left image-wrapper">
								<a class="product-image" href="<?php echo $this->getItemUrl($item); ?>">
								<img src="<?php echo $this->helper('catalog/image')->init($childProduct, 'thumbnail', $item->getSmallImage())->resize(75); ?>" alt="<?php echo $item->getName(); ?>"/></a>
								<div class="product-info">
									<h4 class="title">
										<a href="<?php echo $this->getItemUrl($item); ?>"onclick="saveProductComment(); "><?php echo $this->htmlEscape($product->getName()) ?></a>
										<p>SKU:<? echo $product->getSku() ?></p>
									</h4>					
								</div>
							</td>
							<td class="price-wrapper">
								<?php echo Mage::helper('checkout')->formatPrice($finalPrice) ?>
							</td>
							<td class="text-left">
								<div id="qdiv_<?php echo $item->getId() ?>">
									<input type="number"
										   class="required-entry validate-zero-or-greater qty"
										   size="6"
										   name="quote_request[<?php echo $item->getId() ?>][qty][]"
										   value="<?php echo $item->getQty()*1; ?>"/>
								</div>		
							</td>
							<td class="text-left">
								<a class="remove" title="<?php echo Mage::helper('checkout')->__('Remove item') ?>" href="<?php echo $this->getUrl('qquoteadv/index/delete', array('id' => $item->getId())); ?>">
									<img src="<?php echo $this->getSkinUrl('images/btn_trash.gif') ?>" width="16" height="16" alt="<?php echo Mage::helper('checkout')->__('Remove item') ?>"/>
									<span>Remove</span>
								</a>
								<input type="hidden" name="quote[<?php echo $item->getId() ?>][qty]" value="<?php echo $item->getQty()*1; ?>" size="3"/>
								<input type="hidden" name="quote[<?php echo $item->getId() ?>][attributeEncode]" value="<?php echo base64_encode($item->getAttribute()) ?>"/>
								<input type="hidden" name="quote[<?php echo $item->getId() ?>][product]" value="<?php echo $product->getId() ?>"/>
								<input type="hidden" name="quote[<?php echo $item->getId() ?>][quoteid]" value="<?php echo $item->getId() ?>"/>					
								<input type="hidden" id="quote_id" name="quote_id" value="<?php echo $item->getQuoteId() ?>">
								<input type="hidden" class="input-text" name="quote[<?php echo $item->getId() ?>][product]" value="<?php echo $item->getProductId(); ?>" size="3"/>
								<input type="hidden" class="input-text" name="quote_request[<?php echo $item->getId() ?>][product_id]" value="<?php echo $item->getProductId(); ?>" size="6"/>						
							</td>
							<td class="text-right">
								<?php echo Mage::helper('checkout')->formatPrice($quoteByProduct->getSubtotal()); $quoteSubtotal += $quoteByProduct->getSubtotal(); ?>
							</td>					
						</tr>
						<?php $i++;	endforeach;	?>
						</tbody>
						<tfoot>
						<tr>
							<td class="text-right" colspan="5"><?php echo 'Quote Subtotal: ' . Mage::helper('checkout')->formatPrice($quoteSubtotal); ?></td>
						</tr>
						</tfoot>
					</table>
					<script type="text/javascript">decorateTable('shopping-cart-table')</script>
					<?php echo $this->getChildHtml('qquote.address'); ?>
					<div class="col-lg-12 bg-white">
					   <p>YOU MAY REQUEST A QUOTE WITHOUT ANY OBLIGATIONS</p>
						<div class="button-wrapper">
							<input type='hidden' name='customer[is_quote]' value='1' />
							<input style="display:none;" type='submit' name='submitOrder' id="submitOrder" class='form-button'
								   value="<?php echo $this->__('Request quote') ?>" />
							<button onclick="$('submitOrder').click(); event.preventDefault();  event.stopPropagation();" class="button btn-proceed-checkout btn-checkout"
									title="<?php echo $this->__('Request quote') ?>" type="button"><span><span><?php echo $this->__('Request quote') ?></span></span>
							</button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
    <script type="text/javascript">
        //<![CDATA[
        var quotelistForm = new VarienForm('quotelist');
        function requestShippingProposal() {
            var elmEmail = $('customer:email');
            if (elmEmail.value) {
                // Send quotelist form to another action
                var quoteShipForm = document.getElementById('quotelist');
                // Reset isQuote to 2
                var isQuote = document.getElementById('customer_isQuote');
                isQuote.value = '2';
                quoteShipForm.action = '<?php echo $this->getUrl('qquoteadv/index/quoteShippingEstimate');?>';
                quoteShipForm.submit();
            }
        }
        //]]>
    </script>
	<?php //#show pop-up window
    if (count($productNames) > 0) {
        echo $this->getLayout()->createBlock("core/template")->setTemplate('qquoteadv/quote_lightbox.phtml')->setProductNames($productNames)->toHtml();
    }
    ?>
    <script language="javascript">
        var pool = new Array();
        function addNewLine(itemId, inputName) {
            if (!pool[itemId]) {
                pool[itemId] = 1;
            }

            index = pool[itemId];
            index++;
            pool[itemId] = index;

            var parentElemt = document.getElementById('qdiv_' + itemId);

            var childElem = document.createElement('div');

            childElem.setAttribute("id", 'div_' + itemId + '_' + index);

            childElem.className = "add-row-tier";
            parentDiv = 'div_' + itemId + '_' + index;
            inputField = 'quote_' + itemId + '_' + index;
            link = '<a href="#"  class="btn-remove btn-remove2 btn-qty" title="<?php echo Mage::helper('checkout')->__('Remove item') ?>" onClick="removeElement(\'' + parentDiv + '\', \'' + inputField + '\');
			
			$(\'' + parentDiv + '\').hide()"><?php echo Mage::helper('checkout')->__('Remove item') ?></a>';
            
            childElem.innerHTML = '<input size="6" type="text" name="' + inputName + '"  id="quote_' + itemId + '_' + index + '" value=""  class="required-entry validate-zero-or-greater m5">' + link;

            parentElemt.appendChild(childElem);

            addQtyFieldSaver();
        }

        function removeElement(parentElemt, childElemt) {
            var parentDiv = document.getElementById(parentElemt);

            var childElemt = document.getElementById(childElemt);

            parentDiv.removeChild(childElemt);
        }

        function saveProductComment(action){
            var quoteForm = document.getElementById('quotelist');

            quoteForm.action = '<?php echo $this->getUrl('qquoteadv/index/storeQuote/'); ?>' + action;
            quoteForm.submit();
        }

        //add form field observers
        document.observe('dom:loaded', function(){
            $$('#shopping-cart-table textarea').each(function (el) {
                return $(el).observe('blur', function(e){
                    saveForm();
                });
            });

            addQtyFieldSaver();

            <?php if(!Mage::getStoreConfig('qquoteadv_quote_form_builder/quote_form_remarks/disable_general_remark')): ?>
            $('customer:client_request').observe('blur', function(e){
                saveForm();
            });
            <?php endif; ?>
        });

        function saveForm() {
            var form = $('quotelist').clone(true);

            //update textarea
            var i = 0;
            $('quotelist').select('textarea').each(function (el) {
                form.select('textarea')[i].value = $(el).value;
                i++;
            });

            var action = $('quotelist').action;
            action = action.replace("quoteRequest", "save");

            form.action = action;
            form.request();
        }

        function addQtyFieldSaver() {
            $$('#shopping-cart-table input[type=text]').each(function (el) {
                return $(el).observe('blur', function (e) {
                    saveForm();
                });
            });
        }
    </script>
<?php endif; ?>
