<?php
/**
 * @category    Custom
 * @package     Custom
 * @function    Get Contact Sidebar
 */
?>
<div class="sidebar-section contact-info">
    <h2>Corporate Office</h2>
    <p><strong>Address:</strong> 935-C Cobb Place Blvd. NW Kennesaw, GA 30144 United States</p>
    <p><strong>Phone:</strong> 770-421-0058</p>
    <p><strong>Email:</strong> sales@omni-inc.com</p>
    <p><strong>Fax:</strong> 770-421-0206</p>
    <p><strong>Toll Free:</strong> 1-800-776-4431</p>
</div>
