<?php
/**
 *
 * CART2QUOTE CONFIDENTIAL
 * __________________
 *
 *  [2009] - [2016] Cart2Quote B.V.
 *  All Rights Reserved.
 *
 * NOTICE OF LICENSE
 *
 * All information contained herein is, and remains
 * the property of Cart2Quote B.V. and its suppliers,
 * if any.  The intellectual and technical concepts contained
 * herein are proprietary to Cart2Quote B.V.
 * and its suppliers and may be covered by European and Foreign Patents,
 * patents in process, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Cart2Quote B.V.
 *
 * @category    Ophirah
 * @package     Qquoteadv
 * @copyright   Copyright (c) 2016 Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */
?>
<?php $quoteId = $quoteModel->getId(); 
	$collection = Mage::getModel('ipdetect/quoteextend')->getCollection()
		->addFieldToFilter('quote_id',$quoteId); ?>
<?php if($collection->getSize() > 0): ?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-account"><?php echo Mage::helper('sales')->__('Distributor Info') ?></h4>
    </div>
    <?php $item = $collection->getFirstItem(); $distId = $item->getDistributorId(); ?>
	<?php $distributor = Mage::getModel('distributor/distributor')->load($distId); $data = $distributor->getData();  ?>
	<div class="fieldset">
        <div class="hor-scroll">
			<table class="form-list" cellspacing="0">
				<tbody>
					<?php foreach($data as $k=>$v): ?>
					<tr>
						<td class="label"><label><?php echo ucwords(str_replace('_', ' ', $k)); ?></label></td>	
						<?php if($k == 'image' || $k == 'icon'): ?>
						<td class="value">
						<a href="<?php Mage::getBaseUrl() . '/media/' . $v ?>" onclick="imagePreview('icon_image'); return false;">
							<img src="<?php Mage::getBaseUrl() . '/media/' . $v ?>" id="icon_image" title="<?php echo $v ?>" 
								alt="<?php echo $v ?>" height="22" width="22" class="small-image-preview v-middle">
						</a>						
						</td>
						<?php elseif($k == 'website'): ?>
						<td class="value"><a href="<?php echo $v ?>"><?php echo $v ?></a></td>
						<?php else: ?>
						<td class="value"><?php echo $v ?></td>
						<?php endif; ?>
					</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
        </div>
    </div> 
</div>
<?php endif; ?>