<?php /** @var $this Ophirah_Qquoteadv_Block_Qquote */ ?>
<?php if($this->getQuote()->getData() == array()): ?>

<div class="page-title">
    <h1><?php echo $this->__('Request for Quote') ?></h1>
</div>
<div class="cart-empty">
  <p><?php echo $this->__('No Items to display.'); ?></p>
  <p><?php echo $this->__('Click <a href="%s">here</a> to continue shopping.', $this->getUrl()) ?></p>
</div>

<?php else: ?>

<?php 
    $productNames = $this->getNotSalableProductNames($this->getQuote());
    $currentCountry = Mage::getModel('core/session')->getData('current_country');
    if(in_array($currentCountry['code'], array('CA','US'))):
        $allowedCountry = true;
    else:
        $allowedCountry = false;
    endif
?>
<div class="page-title title-buttons">
    <h1><?php echo $this->__('Request for Quote') ?></h1>
    <?php if($this->displayAssignedTo()): ?>
        <div class="assigned-to">
            <?php if(Mage::helper('qquoteadv')->getAdminUser() !== null): ?>
                <?php if($this->isAssignPreviousEnabled()): ?>
                    <?php if($this->helper('customer')->isLoggedIn()): ?>
                        <?php
                        $customerData = Mage::getSingleton('customer/session')->getCustomer();
                        echo $this->__('Quote will be assigned to <strong>%s</strong>', Mage::helper('qquoteadv')->getAdminUser(Mage::helper('qquoteadv')->getPreviousAssignedAdmin(null, $customerData->getId()))->getName()); ?>
                     <?php else: ?>
                        <?php echo $this->__('If the end user has no previous assigned sales representative the quote will be assigned to <strong>%s</strong>.', $this->getAdminUser()->getName()); ?>
                    <?php endif; ?>
                <?php else: ?>
                    <?php echo $this->__('Quote will be assigned to <strong>%s</strong>', $this->getAdminUser()->getName()); ?>
                <?php endif; ?>
            <?php endif; ?>
        </div>
    <?php endif; ?>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<form method='post' id="quotelist" name="quotelist" action='<?php echo $this->getUrl('qquoteadv/index/quoteRequest', array('_secure' => true)) ?>' >
    <?php if($this->displayAssignedTo() && $this->getAdminUser() !== null): ?>
        <input type="hidden" name="user_id" value="<?php echo $this->getAdminUser()->getId(); ?>" />
    <?php endif; ?>
    <?php $dist = Mage::getSingleton('core/session')->getData('current_distributer'); ?>
    <?php if(!empty($dist)): ?>
	<input type="hidden" name="dist_id" id="dist_id" value="<?php echo $dist['id'] ?>">
	<?php endif; ?>

    <table id="shopping-cart-table" class="data-table cart-table">
<!--         <col width="30" />
        <col width="75" />
        <col />
        <col width="10" />
        <col width="250"/>
        <col width="60" />
        <col width="60" /> -->
        <thead>
           <tr>
            <th>
                <span class="product-name quote"><?php echo $this->__('Product Name') ?></span>
                <span class="qty quote"><?php echo $this->__('Qty') ?></span>
                <!-- <span class="unit-price quote"><?php echo $this->__('Unit price') ?></span> -->
                <span class="remove quote"><?php echo $this->__('Remove') ?></span>
            </th>
           </tr>
        </thead>
        <tbody>
            <?php
            $i = 0;
            foreach($this->getQuote() as $item):

                $product = $this->getProduct($item->getProductId());
            
                if($product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_CONFIGURABLE) {
                    $childProduct = Mage::getModel('qquoteadv/qqadvproduct')->getConfChildProduct($item->getId());
                } else {
                    $childProduct = $product;
                }
                ?>
                <tr>
                    <td class="last">
                        <div class="td first quote">
                            <a class="product-image" href="<?php echo $product->getProductUrl(); ?>"><img src="<?php echo $this->helper('catalog/image')->init($childProduct, 'thumbnail', $item->getSmallImage())->resize(75); ?>" alt="<?php echo $item->getName(); ?>" />
                            </a>
                        </div>
                        <div class="td desc quote">
                            <h4 class="title">
                                <?php if (1): //$product->hasProductUrl()):?>
                                    <a href="<?php echo $product->getProductUrl() ?>"><?php echo $this->htmlEscape($product->getName()) ?></a>
                                <?php else: ?>
                                    <?php echo $this->htmlEscape($product->getName()) ?>
                                <?php endif; ?>
                            </h4>
                            <?php
                                if($product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_BUNDLE || $product->isConfigurable()  || $product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_SIMPLE):
                                    $quoteByProduct = Mage::helper('qquoteadv')->getQuoteItem($product, $item->getAttribute(), null, $item);

                                    foreach($quoteByProduct->getAllItems() as $_item) {
                                        if( $_item->getProductId() == $product->getId() ) {
                                            echo $this->getItemHtml($_item);
                                        }
                                    }
                                    
                                    $qty = $quoteByProduct->getItemsQty();
                                    
                                    // Select price with or without tax
                                    if(Mage::getStoreConfig('tax/calculation/price_includes_tax') == 1):
                                        $_finalPrice = $quoteByProduct->getGrandTotal() / ($qty>0?$qty:1);
                                    elseif($quoteByProduct->getSubtotal()):
                                        $_finalPrice = $quoteByProduct->getSubtotal() / ($qty>0?$qty:1);    
                                    else:
                                        $_finalPrice = $product->getFinalPrice() / ($qty>0?$qty:1);          
                                    endif;
                             endif; ?>
                        </div>
                        <div style="display:none;">
                            <?php print_r(unserialize($item->getAttribute())) ?>
                        </div>
                        <div class="td qty quote">
                            <div id="qdiv_<?php echo $item->getId() ?>">
                                <p style="text-align:center;"><?php echo (int)$item->getQty() ?></p>
                            </div>
                            <div>
                                <?php if($this->getShowTrierOption()) : ?>
                                    <a class="pad" href="#" onClick="addNewLine(<?php echo $item->getId() ?>, 'quote_request[<?php echo $item->getId() ?>][qty][]'); return false;"><?php echo $this->__('Add Qty') ?>
                                    </a>
                                <?php endif; ?>
                            </div>
                            <input type="hidden" name="quote[<?php echo $item->getId() ?>][qty]" value="<?php echo $item->getQty(); ?>" />&nbsp;
                            <input type="hidden" name="quote[<?php echo $item->getId() ?>][attributeEncode]" value="<?php echo base64_encode($item->getAttribute()) ?>" />
                            <input type="hidden" name="quote[<?php echo $item->getId() ?>][product]" value="<?php echo $product->getId() ?>" />
                            <input type="hidden" name="quote[<?php echo $item->getId() ?>][quoteid]" value="<?php echo $item->getId() ?>" />
                        </div>
                        <!-- <div class="td price quote">
                        <?php if($quoteByProduct->getGrandTotal()!=0 && $allowedCountry) {
                                $priceDisplay = 'block';
                                $noPriceDisplay = 'none';
                            }else{
                                $priceDisplay = 'none';
                                $noPriceDisplay = 'block';
                            }
                        ?>
                            <div class="price-box" style="display:<?php echo $priceDisplay ?>">
                                <?php if (Mage::helper('qquoteadv/not2order')->getShowPrice($product)): ?>
                                <?php echo Mage::helper('checkout')->formatPrice($_finalPrice)?>
                                <?php endif; ?>
                            </div>
                            <div class="alt-no-price" style="display:<?php echo $noPriceDisplay ?>">
                                -
                            </div>
                        </div> -->
                        <div class="td last quote">
                            <input type="hidden" id="quote_id" name="quote_id" value="<?php echo $item->getQuoteId() ?>">
                            <input type="hidden" class="input-text" name="quote[<?php echo $item->getId() ?>][product]" value="<?php echo $item->getProductId(); ?>" />
                            <input type="hidden" class="input-text" name="quote_request[<?php echo $item->getId() ?>][product_id]" value="<?php echo $item->getProductId(); ?>" />
                            <a title="<?php echo $this->__('Remove item')?>" href="<?php echo $this->getUrl('qquoteadv/index/delete',array('id'=>$item->getId())); ?>" class="btn-remove btn-remove2" ></a>
                        </div>
                    </td>
                </tr>
                <?php
                $i++;
            endforeach;
            ?>
            </tbody>
            <tfoot>
            <tr>
                <td class="a-right">
                    <?php $action = "setLocation('".$this->getUrl('qquoteadv/index/switch2Order')."');";

                    if(count($productNames)>0){
                        $action = 'initMsg();';
                    }
                    ?>

                    <?php $action = "setLocation('".$this->getUrl('qquoteadv/index/clearQuote')."');";?>
                </td>
            </tr>
            </tfoot>

        </table>
        <script type="text/javascript">decorateTable('shopping-cart-table')</script>

    <?php echo $this->getChildHtml('qquote.address'); ?>
       <div class="box">
       <p>YOU MAY REQUEST A QUOTE WITHOUT ANY OBLIGATIONS</p>
       <hr><br>
        <div style="float:left;">
            <input type='hidden' name='customer[is_quote]' value='1' />
            <input style="display:none;" type='submit' name='submitOrder' id="submitOrder" class='form-button'
                   value="<?php echo $this->__('Request quote') ?>" />
            <button onclick="$('submitOrder').click(); event.preventDefault();  event.stopPropagation();" class="button btn-proceed-checkout btn-checkout"
                    title="<?php echo $this->__('Request quote') ?>" type="button"><span><span><?php echo $this->__('Request quote') ?></span></span>
            </button>
        </div>
        <div style="clear:both"></div>
        </div>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var quotelistForm = new VarienForm('quotelist');
    new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>);
    $('country').addClassName('w224');
        new RegionUpdater('shipping_country', 'shipping_region', 'shipping_region_id', <?php echo $this->helper('directory')->getRegionJson() ?>);
    $('shipping_country').addClassName('w224');
//]]>
</script>


<?php 
//#show pop-up window
if(count($productNames)>0){
    echo $this->getLayout()->createBlock("core/template")->setTemplate('qquoteadv/quote_lightbox.phtml')->setProductNames($productNames)->toHtml(); 
}
?>


<script language="javascript">

var pool = new Array();

function addNewLine(itemId, inputName){
    if (!pool[itemId]){
       pool[itemId] = 1;
   }

   index = pool[itemId];
   index++;
   pool[itemId] = index;

   var parentElemt = document.getElementById('qdiv_'+itemId);
   var childElem = document.createElement('div');
   childElem.setAttribute("id",'div_' + itemId + '_' + index);
   parentDiv='div_' + itemId + '_' + index;
   inputField='quote_' + itemId + '_' + index;
   link = '&nbsp;&nbsp;<a style="text-decoration:none;" href="#"  onClick="removeElement(\''+parentDiv+'\', \''+inputField+'\'); $(\''+parentDiv+'\').hide()"><img style="vertical-align: bottom;bottom;width:19px;height:18px;" src="<?php echo $this->getSkinUrl('images/minus-icon.png')?>"></a>';

   childElem.innerHTML = '<input size="6" type="text" name="'+inputName+'"  id="quote_' + itemId + '_' + index +'" value=""  class="required-entry validate-zero-or-greater required-entry input-text m5">'+link;

   parentElemt.appendChild(childElem);
}

function removeElement(parentElemt, childElemt) {
  var parentDiv = document.getElementById(parentElemt);
  var childElemt = document.getElementById(childElemt);
  parentDiv.removeChild(childElemt);
}
</script>
<?php endif; ?>
