<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<?php if (Mage::getStoreConfig('news/settings/news_show')): ?>
    <?php
    $store_id = Mage::app()->getStore()->getId();
    $_NewsCollection = Mage::getModel('news/news')->getCollection()->addFieldToFilter('status', '1')->addStoreFilter($store_id);

    $_NewsCollection = $this->getCollection()->addStoreFilter($store_id);

    $query = $this->getRequest()->getParam('keyword');
    ?>

    <div class="page-title" >
        <h1><?php if ($query) {
        echo $this->__('Search results for ') . "'" . $query . "'";
    } else {
        echo $this->__('News');
    } ?></h1>
    </div>
    <?php echo $this->getPagerHtml(); ?>
    <?php $newstotal = $_NewsCollection->count(); ?>
            <?php if ($_NewsCollection->getSize()): ?>
        <div class="news-content">
            <ul class="news">
        <?php $i = 0;
        foreach ($_NewsCollection as $_news): $i++;
            ?>
                    <li class="items">
                        <div class="news-title">
                            <h2 class="left"><?php echo $_news->getTitle(); ?></h2>
                            <div class="right news-date"><?php echo date('l , jS F Y', strtotime($_news->getStartDate())); ?></div>
                            <div class="clearer">&nbsp;</div>
                        </div>

                        <div class="news-details">
                            <div class="news-image">
                                <?php if ($_news->getThumbnail()): ?>
                <?php $marginPosition = ($_news->getThumbnailAlign() == "left") ? "float: left; margin-right: 10px;" : "float: right; margin-left: 10px;"; ?>
                                    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $_news['thumbnail']; ?>" align="left" style="<?php echo $marginPosition; ?>" alt="Thumbnail" width="100" />
                                <?php endif; ?>
                            </div>
                            <div class="news-desc"><?php
                    $helper = Mage::helper('news/wysiwyg_images');
                    $processor = $helper->getPageTemplateProcessor();
                    $html = $processor->filter($_news->getText());
                    echo $html;
                                ?>
                            </div> 

                            <?php
                            $fbtitle = $_news->getTitle();
                            $fburl = Mage::getBaseUrl() . 'news';
                            $fbcontent = str_replace("<p>", "", $_news->getText());
                            $marginPosition = ($_news->getThumbnailAlign() == "left") ? "float: left; margin-right: 10px;" : "float: right; margin-left: 10px;";
                            $fbimg = '<img src="' . $_news->getThumbnailResize(100) . '" align="' . $_news->getThumbnailAlign() . '" style="' . $marginPosition . '" alt="Thumbnail"/ >';
                            $socialImage = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $_news['thumbnail'];
                            $title = urlencode($fbtitle);
                            $url = urlencode($fburl);
                            $image = urlencode($socialImage);
                            $summary = urlencode($fbcontent);
                            ?>
                            <div class="social-buttons">
            <?php if (Mage::getStoreConfig('news/social_settings/news_facebook_show') == '1'): ?>
                                    <a onClick="window.open('http://www.facebook.com/sharer.php?s=100&p[title]=<?php echo $title; ?>&p[summary]=<?php echo $summary; ?>&p[url]=<?php echo $url; ?>&p[images][0]=<?php echo $image; ?>','sharer','toolbar=0,status=0,width=548,height=325');" href="javascript: void(0)">
                                        <img height="20" alt="Share on Facebook" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) . "skin/frontend/default/default/news/images/fbshare.png" ?>">
                                    </a>
                                    &nbsp;&nbsp;
                                   <?php endif; ?>
                                    <?php if (Mage::getStoreConfig('news/social_settings/news_googleplus_show') == '1'): ?>
                                    <a href="https://plus.google.com/share?url={http://115.112.143.170/ECO/mag/demo/index.php/testimonials/}" onclick="javascript:window.open(this.href,
                                        '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');return false;"><img
                                            src="https://www.gstatic.com/images/icons/gplus-32.png" alt="Share on Google+" height="20"/></a>
                    <?php endif; ?>
                            </div>
                            <div style="clear:both;"></div>	
                    </li>
        <?php endforeach; ?>

        <?php if ($newstotal != '0'): ?>
                    <script src="http://w.sharethis.com/button/buttons.js" type="text/javascript"></script>
                    <div class="share-main">
                        <div class="left">
                            <span class="st_fblike_hcount">&nbsp;</span>
                            <span class="st_twitter_hcount">&nbsp;</span>
                            <span class="st_pinterest_hcount">&nbsp;</span>
                            <span class="st_plusone_hcount">&nbsp;</span>
                        </div>
                        <div style="clear:both;"></div>
                        <div style="height:10px">&nbsp;</div>
                    </div>
        <?php endif; ?> 
            </ul> 
        </div>
    <?php endif; ?>
    <?php if ($newstotal == '0'): ?>
          <p class="note-msg">               
          <?php if($query): ?>             
                <?php echo $this->__('Your search returns no results.'); ?>
          <?php else: ?>
                  <?php echo $this->__('There are no news for this section'); ?>      
          <?php endif; ?>              
          </p>    
    <?php endif; ?>                     
<?php endif; ?>