<style>
.storelocator .search-result .row {display: -webkit-box;display: -ms-flexbox;display: flex;-ms-flex-wrap: wrap;flex-wrap: wrap;}
.storelocator .search-result .item {display: flex; margin: 0 auto 20px;  width: 33.3%; padding: 0 2%; box-sizing: border-box;}
.storelocator .search-result .item .item-wrapper {display: flex; margin-bottom:2%;width: 100%; -webkit-box-orient: vertical; -webkit-box-direction: normal; -ms-flex-direction: column; flex-direction: column;}
.storelocator .search-result .item .item-wrapper .store-info {color: #78777a; -webkit-box-flex: 1; -ms-flex: 1 0 auto; flex: 1 0 auto;}
.storelocator .search-result .item .item-wrapper .store-info .label {font-family: myriadpro_bold;}
.storelocator .search-result .item .item-wrapper .store-info p {margin: 0;}
.storelocator .search-result .item .item-wrapper .store-name {color: #2B428D; font-family: myriadpro_bold; font-size: 1.2em;}
.storelocator .search-result .item .item-wrapper .store-address {margin: 10px 0;}
.storelocator .search-result .item .item-wrapper .phone a {color: #4eb4d0;}
.storelocator .search-result .item .item-wrapper .extend-link .website {padding: 6px 40px;}

/* 768px <= width < 1024px */

@media only screen and (min-width: 768px) and (max-width: 1024px) {
	.storelocator .search-result .item {width: 50%;}
	.storelocator .search-result .item .item-wrapper {width: 100%;}
}

/* 320px <= width < 768px */

@media only screen and (min-width: 320px) and (max-width: 767px) {
	.storelocator .search-result .item {width: 100%;}
	.storelocator .search-result .item .item-wrapper {width: 100%;}
}

/** internal **/
.tooltips .main {position: inherit;}
.tooltips .main-container {position: inherit;}

</style>

<script>
        var getAllDistributors = function() {
            console.log('working for view!');
            var selectedCountry = localStorage.getItem('countryCode');
            $j.ajax({
                url: 'http://omni3.mkmage.com/distributor/index/index?code=' + selectedCountry,
                type: "GET",
                success: function(data) {
                    results = JSON.parse(data);
                    var dist;
console.log('wroked!!!!!! again!!!!');
                    for(var prop in results) {
                        if(prop === 'distributers'){
                            dist = results[prop];
                        }
                    }
                    buildDistList(dist);
                }
            });
        };
        getAllDistributors();

        function buildDistList(arr){
            var list = '';
            arr.forEach(function(dist) {
                list += '<div class="item"><div class="item-wrapper tab-content-cms"><div class="store-info itemscope itemtype="http://schema.org/LocalBusiness"">';
                list += '<div class="store-name">'+ dist.title +'</div>';
                list += '<div class="phone"><span class="label">Phone:</span><p itemprop="telephone"><a href="tel:'+ dist.phone+'">'+dist.phone +'</a></p></div>';
                list += '<address class="store-address"><span class="label">Address:</span><p itemprop="address">'+ dist.street +', '+ dist.city +', '+ dist.region +'</p></address>';
                list += '</div>';
                list += '<div class="extend-link"><a target="_blank"  itemprop="url" href="'+ dist.website +'" class="btn btn-solid website">Website</a></div>';
                list += '</div>';
                list += '</div>';
            });
            $j('.search-result .row').empty();
            $j('.search-result .row').append(list);
        };

</script>


   <div class="container storelocator">
        <div class="search-result">
        <div class="row" style="min-height: 200px;">
            <h3 style="text-align:center; padding: 20px;">Loading Distributors</h3>
        </div>
        </div>
    </div>
    <!-- <div class="back-to-top"><a href="#filter"><?php echo $this->__('Back to Top')?></a></div> -->