<div class="row top">
	<div class="container">
		<span>QUESTIONS?</span>
		<button class="btn btn-solid btn-lg btn-green" onclick="window.location.href='/contacts/'">CONTACT AN EXPERT</button>
		<p class="lead">
			<small>Fill out form so our sales team can contact you.</small>
		</p>
	</div> 
</div>
<div class="row middle">
	<div class="container">
		<div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
			<div class="logo-wrap">
				<img class="logo" src="<?php echo Mage::getDesign()->getSkinUrl() . 'images/omni-logo-new.svg' ?>" alt="logo">
			</div>
			<h4><strong>Omni International</strong></h4>
			<address>
				<p>935-C Cobb Place Blvd.</p>
				<p>Kennesaw GA, 30144</p>
				<p>United States</p>
			</address>
			<span class="email">
				<strong>Email</strong>
				<a href="mailto:sales@omni-inc.com">sales@omni-inc.com</a>
			</span>
		</div>
		<div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
			<h4>Products</h4>
			<ul>
				<li><a href="/high-shear-lab-homogenizers.html">Rotor Stator Homogenizers</a></li>
				<li><a href="/ultrasonic-cell-disruptors.html">Ultrasonic Homogenizers</a></li>
				<li><a href="/bead-mill-cell-lysing.html">Bead Mill Homogenizers</a></li>
				<li><a href="/multi-sample-lab-homogenizers.html">Automated Homogenizers</a></li>
				<li><a href="/consumables.html">Consumables</a></li>
				<li><a href="/accessories.html">Accessories</a></li>
			</ul>
		</div>
		<div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
			<h4>Support &amp; Resources</h4>
			<ul>
				<li><a href="/customer/account/">Your Account</a></li>
				<li><a href="/application/application">Application Database</a></li>
				<li><a href="/protocol/application">Protocol Database</a></li>
				<li><a href="/videos">Videos</a></li>
				<li><a href="/warranty-registration/">Warranty Registration</a></li>
				<li><a href="/distributor-locator/">Distributor Locator</a></li>
			</ul>
		</div>
		<div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
			<h4>About Omni</h4>
			<ul>
				<li><a href="/about-omni/">About Omni</a></li>
				<li><a href="/news/">Newsroom</a></li>
				<li><a href="/careers/">Careers</a></li>
			</ul>
		</div>
	</div>
</div>
<div class="row bottom">
	<div class="container">
		<div class="row-inline">
			<div class="col-lg-6 inline-elements padding-0">
				<span>Copyright © 2018 OMNI, INC. ALL RIGHTS RESERVED.</span>
			</div>
			<div class="col-lg-6 inline-elements padding-0 pull-right">
				<div class="pull-right social-icons">
					<ul class="social-icons list-group">
						<li class="facebook list-group-item"><a href="https://www.facebook.com/OMNIInternationalInc/" target="_blank">Facebook</a></li>
						<li class="twitter list-group-item"><a href="https://twitter.com/OmniInc" target="_blank">Twitter</a></li>
						<li class="linkedin list-group-item"><a href="https://www.linkedin.com/company/omni-international_2/" target="_blank">Linkedin</a></li>
						<li class="instagram list-group-item"><a href="https://www.instagram.com/omni_international/ " target="_blank">Instagram</a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>					
<div class="loading"></div>