<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0 " />
<meta name="google-site-verification" content="AkLz6AV9QFs84jCT5SREIj3bsX7H6udJZrWijhdaheM" />
<meta name="google-site-verification" content="Ax0nvtnGWl45SE8qRjK7o8xSpxVwizfjL3mo9FRMnSI" />
  <meta name="google-translate-customization" content="86891d37e9507069-65398aa04931c2f8-g2e9ef316f8e456fb-e" />
<title><?php echo $this->getTitle() ?></title>
<meta name="description" content="<?php echo htmlspecialchars($this->getDescription()) ?>" />
<meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()) ?>" />
<meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()) ?>" />
<link rel="icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<link rel="shortcut icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />

<!--[if lt IE 7]>
<script type="text/javascript">
//<![CDATA[
    var BLANK_URL = '<?php echo $this->helper('core/js')->getJsUrl('blank.html') ?>';
    var BLANK_IMG = '<?php echo $this->helper('core/js')->getJsUrl('spacer.gif') ?>';
//]]>
</script>
<![endif]-->
<?php echo $this->getCssJsHtml() ?>
<?php echo $this->getChildHtml() ?>
<?php echo $this->helper('core/js')->getTranslatorScript() ?>
<?php echo $this->getIncludes() ?>
<script src="//cdnjs.cloudflare.com/ajax/libs/Swiper/4.1.6/js/swiper.min.js"></script>
<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/Swiper/4.1.6/css/swiper.css">
<script src="//cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js"></script>
<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css">
<script>
(function($jq){
	$jq(document).ready(function(){
		var successMsgs = $jq('.messages .success-msg');
		if (successMsgs.text().indexOf('added to your shopping cart.') > -1) {
			$jq('.block-cart').click();
		}
	});
	jQuery(window).scroll(function(){
		var sticky = jQuery('body'),
		scroll = jQuery(window).scrollTop();
		//console.log(scroll);
		if ($jq(window).width() > 767){ 
			if (scroll >= 156) sticky.addClass('fixed');
			else sticky.removeClass('fixed');
		} else {
			if (scroll >= 85) sticky.addClass('fixed-mobile');
			else sticky.removeClass('fixed-mobile');
		}
	});
})(jQuery);
</script>